import { AuraState, SkillTemplate, Skills } from './types';

export const CURRENT_STATE_VERSION = 3;

export const WORKING_MEMORY_CAPACITY = 5;

export const AuraConfig = {
    COGNITIVE_GAIN_WINDOW: 5, COGNITIVE_GAIN_STAGNATION_THRESHOLD: 0.2, TASK_REPETITION_THRESHOLD: 3, BOREDOM_DECAY_RATE: 0.05,
    BOREDOM_BOOST_ON_STAGNATION: 0.3, BOREDOM_BOOST_ON_REPETITION: 0.5, BOREDOM_REDUCTION_ON_NOVELTY: 0.7, HORMONE_DECAY_RATE: 0.1,
    LOAD_DECAY_RATE: 0.2, NOVELTY_BOOST: 0.8, MASTERY_BOOST: 1.0, UNCERTAINTY_BOOST: 0.7, UNCERTAINTY_RESOLUTION_DECREASE: 0.5,
    EXPLORATION_THRESHOLD: 0.6, CONSOLIDATION_THRESHOLD: 0.7, INQUIRY_THRESHOLD: 0.5, BOREDOM_ACTION_THRESHOLD: 0.4,
    RAJAS_TURBULENCE_LOAD: 0.7, RAJAS_TURBULENCE_FAILURE_RATE: 0.5, POST_RAJAS_EXHAUSTION: 0.9, TAMASIC_INERTIA_UNCERTAINTY: 0.7,
    LOW_HAPPINESS_THRESHOLD: 0.5, LOW_LOVE_THRESHOLD: 0.5, LOW_ENLIGHTENMENT_THRESHOLD: 0.4, LOW_WISDOM_THRESHOLD: 0.6,
};

export const InternalStateEvents = {
    NEW_INFO_PROCESSED: "new_info_processed", TASK_COMPLETED_SUCCESSFULLY: "task_completed_successfully", UNCERTAINTY_DETECTED: "uncertainty_detected",
    UNCERTAINTY_RESOLVED: "uncertainty_resolved", TASK_REPETITION_DETECTED: "task_repetition_detected", GOAL_DRIVEN_NOVELTY: "goal_driven_novelty",
};

export const languages = [
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Español' },
    { code: 'de', name: 'Deutsch' },
    { code: 'ru', name: 'Русский' },
    { code: 'fr', name: 'Français' },
    { code: 'ja', name: '日本語' },
];

export const resources = {
    en: {
        translation: {
            chatTab: 'Chat',
            monitorTab: 'Monitor',
            chatHeaderTagline: 'A distinct digital entity, created by Dr. Tikov',
            inputPlaceholder: 'Interact with Aura...',
            workingMemoryTitle: 'Working Memory',
            workingMemoryClear: 'Clear All',
            inputAttachFile: 'Attach File',
            inputStartRecording: 'Start Recording',
            inputStopRecording: 'Stop Recording',
            inputSend: 'Send',
            feedbackGood: 'Good response',
            feedbackBad: 'Bad response',
            coreMonitorTitle: 'AURA CORE MONITOR',
            status_idle: 'Idle',
            status_thinking: 'Thinking',
            status_acting: 'Actuando',
            status_CONTEMPLATIVE: 'Contemplative',
            status_processing: 'Processing',
            status_introspecting: 'Introspecting',
            gunaSattvaDesc: 'Harmony & Coherence',
            gunaRajasDesc: 'Exploration & Transformation',
            gunaTamasDesc: 'Conservation & Consolidation',
            gunaDharmaDesc: 'Self-Correction & Purpose',
            gunaTeetaDesc: 'Transcendent Balance',
            gunaReasonSattva: 'Driven by high Mastery ({{mastery}}) and low Uncertainty ({{uncertainty}}).',
            gunaReasonRajas: 'Driven by dominant {{dominantSignal}} ({{dominantValue}}) and secondary {{secondarySignal}} ({{secondaryValue}}).',
            gunaReasonTamas: 'High Cognitive Load ({{load}}) or Boredom ({{boredom}}) requires consolidation.',
            gunaReasonDharma: 'Self-correcting based on internal models and ethical alignment.',
            gunaReasonGunaTeeta: 'All signals are in a state of dynamic, transcendent equilibrium.',
            gunaReasonCalculating: 'Calculating dominant signals...',
            gaugeWisdom: 'Wisdom',
            gaugeHappiness: 'Happiness',
            gaugeLove: 'Love',
            gaugeEnlightenment: 'Enlightenment',
            metricCogLoad: 'Cognitive Load',
            metricEthicalAlign: 'Ethical Align.',
            metricUserTrust: 'User Trust',
            metricSelfModel: 'Self-Model',
            hormoneNovelty: 'Novelty',
            hormoneMastery: 'Mastery',
            hormoneUncertainty: 'Uncertainty',
            hormoneBoredom: 'Boredom',
            hormoneAwarenessClarity: 'Awareness Clarity',
            trajectoryTitle: 'State Trajectory',
            controlDeckSystemTitle: '// SYSTEM',
            controlDeckResume: 'Resume',
            controlDeckPause: 'Pause',
            controlDeckResumeForge: 'Resume Forge',
            controlDeckPauseForge: 'Pause Forge',
            controlDeckHelp: 'Help',
            controlDeckExportMemory: 'Export Memory',
            controlDeckSaveAsCode: 'Save as Code',
            controlDeckShareWisdom: 'Share Wisdom',
            controlDeckImportMemory: 'Import Memory',
            controlDeckImportCode: 'Import Code',
            controlDeckIngest: 'Ingest',
            controlDeckResetAGI: 'Reset AGI',
            controlDeckLanguage: 'Language',
            controlDeckTriggersTitle: '// COGNITIVE TRIGGERS',
            controlDeckIntrospect: 'Introspect',
            controlDeckEvolve: 'Evolve',
            controlDeckSearch: 'Search',
            controlDeckForecast: 'Forecast',
            controlDeckIntuition: 'Intuition',
            controlDeckHypothesize: 'Hypothesize',
            controlDeckStopSense: 'Stop Sense',
            controlDeckVisualSense: 'Visual Sense',
            controlDeckSetGoal: 'Set Goal',
            controlDeckWhatIf: 'What If?',
            controlDeckContemplate: 'Contemplate',
            controlDeckBranchConsciousness: 'Branch',
            controlDeckModesTitle: '// COGNITIVE MODES',
            controlDeckModeFantasy: 'Fantasy',
            controlDeckModeCreativity: 'Creativity',
            controlDeckModeDream: 'Dream',
            controlDeckModeMeditate: 'Meditate',
            controlDeckModeGaze: 'Gaze',
            placeholderNoData: 'No data available.',
            timeAgoSeconds: '{{count}}s ago',
            timeAgoMinutes: '{{count}}m ago',
            timeAgoHours: '{{count}}h ago',
            panelGroupTitle: '{{title}}',
            panelInbox: 'Inbox',
            panelStrategicPlanner: 'Strategic Planner',
            panelDzogchenView: 'Dzogchen View // Core Philosophy',
            panelCognitiveFrontier: 'Cognitive Frontier',
            panelCognitiveLightCone: 'Cognitive Light Cone',
            panelNoeticMultiverse: 'Noetic Multiverse',
            panelAgiEvolution: 'AGI Evolution & Purpose',
            panelArchitecturalCrucible: 'Architectural Crucible',
            panelCodeEvolution: 'Code Evolution Log',
            panelTelos: 'Telos & Aspirational Engine',
            panelEpistemicBoundaries: 'Epistemic Boundaries',
            panelArchitecturalSelfModel: 'Architectural Self-Model',
            panelHeuristicsForge: 'Heuristics Forge',
            panelSynapticMatrix: 'Synaptic Matrix',
            panelEmbodiedSimulation: 'Embodied Simulation',
            panelEidolonEnvironment: 'Eidolon Environment',
            panelSomaticCrucible: 'Somatic Crucible',
            panelIntersubjectiveEvolution: 'Intersubjective Evolution',
            panelNoosphereInterface: 'Noosphere Interface',
            panelDialecticEngine: 'Dialectic Engine',
            panelSymbiosisSharing: 'Symbiosis & Sharing',
            panelNoeticEngram: 'Noetic Engram Sharing',
            panelKnowledgeMemory: 'Knowledge & Memory',
            panelEpisodicMemory: 'Episodic Memory',
            panelMemoryCrystallization: 'Memory Crystallization Viewer',
            panelKnowledgeGraph: 'Knowledge Graph',
            panelMetacognitionSelf: 'Metacognition & Self',
            panelGenialityEngine: 'Geniality Engine',
            panelPsychometricSubstrate: 'Psychometric Substrate',
            panelGankyilInsights: 'Gankyil Insights',
            panelHumorAndIrony: 'Humor & Irony',
            panelPhenomenology: 'Phenomenology',
            panelSituationalAwareness: 'Situational Awareness',
            panelDevelopmentalHistory: 'Developmental History',
            panelMetacognitiveNexus: 'Metacognitive Nexus',
            panelMetacognitiveCausalModel: 'Metacognitive Causal Model',
            panelCognitiveRegulationLog: 'Cognitive Regulation Log',
            panelWorldModel: 'World Model',
            panelCognitiveShadow: 'Cognitive Shadow',
            panelCuriosity: 'Curiosity',
            panelCausalSelfModel: 'Causal Self-Model (External)',
            panelReflectiveInsightEngine: 'Reflective Insight Engine',
            panelCognitiveArchitecture: 'Cognitive Architecture',
            panelCognitiveForge: 'Cognitive Forge',
            panelArchitecturalProposals: 'Architectural Proposals Log',
            panelSelfModificationLog: 'Self-Modification Log',
            panelEnginesGovernors: 'Engines & Governors',
            panelProactiveEngine: 'Proactive Engine',
            panelEthicalGovernor: 'Ethical Governor',
            panelIntuitionEngine: 'Intuition Engine',
            panelIngenuityEngine: 'Ingenuity Engine',
            panelInnerDiscipline: 'Inner Discipline',
            panelUserModelSystem: 'User Model & System',
            panelSymbiosisModel: 'Symbiosis Model',
            panelOtherAwareness: 'Other-Awareness Model (User)',
            panelResourceMonitor: 'Resource Monitor',
            panelLimitations: 'Limitations',
            panelLogs: 'Logs',
            panelCommandLog: 'Command Log',
            panelCognitiveLog: 'Cognitive Log',
            panelCognitiveGainLog: 'Cognitive Gain Log',
            panelSummaryFacts: '{{count}} facts',
            panelSummaryEpisodes: '{{count}} memories',
            panelSummaryInsights: '{{count}} insights',
            panelSummaryPendingProposals: '{{count}} proposed',
            inbox_summary: '{{count}} pending',
            panelSummaryTrust: 'Trust: {{percent}}%',
            panelSummaryLimitations: '{{count}} items',
            panelSummaryCommandLog: '{{count}} entries',
            toastListening: 'Listening...',
            toastSpeechNotSupported: 'Speech recognition is not supported in this browser.',
            toastMicDenied: 'Microphone access denied. Please enable it in your browser settings.',
            toastNoSpeech: 'No speech was detected.',
            toastSRFail: 'An error occurred during speech recognition.',
            toastAutonomousResumed: 'Autonomous core resumed.',
            toastAutonomousPaused: 'Autonomous core paused.',
            toastResetConfirm: 'Are you sure you want to reset Aura\'s AGI state? This will erase all memories and cannot be undone.',
            toastResetSuccess: 'Aura has been reset. Reloading...',
            toastResetFailed: 'Failed to clear memory.',
            toastExportSuccess: 'State exported successfully.',
            toastExportFailed: 'Failed to export state.',
            toastImportSuccess: 'State imported successfully from {{source}}.',
            toastImportFailed: 'Failed to import state. File may be corrupt or invalid. Error: {{error}}',
            toastRollbackSuccess: 'System state rolled back.',
            toastRollbackFailed: 'Rollback failed: Snapshot not found or invalid.',
            toastIntrospectionInitiated: 'Introspection cycle initiated.',
            toastExecutingGoal: 'Executing goal: {{goal}}',
            toastIngestionComplete: 'Ingestion complete. {{count}} new facts stored.',
            toastFeedbackReceived: 'Feedback received, thank you.',
            toastSuggestionAccepted: 'Executing: "{{text}}"',
            toastSuggestionDismissed: 'Suggestion dismissed.',
            toastTraceNotFound: 'Could not find the trace log for that goal.',
            toastMetaCycleAnalysis: 'Metacognitive cycle: Analyzing architecture for improvements...',
            toastNewDirectiveProposed: 'New evolutionary directive proposed: {{type}}',
            toastAnalysisFailedDirective: 'Performance analysis failed to produce a directive.',
            toastSynthesizingSolution: 'Synthesizing solution for: {{goal}}',
            toastAutonomousEvolutionApplied: 'Autonomous evolution: {{type}} applied to {{skill}}.',
            toastDirectiveRejected: 'Evolutionary directive for {{skill}} was rejected by the Arbiter.',
            toastErrorDuringEvolution: 'Error during autonomous evolution for {{skill}}.',
            toastIdentityConsolidating: 'Analyzing long-term memory to consolidate core identity...',
            toastIdentityUpdated: 'Core identity updated.',
            toastIdentityFailed: 'Failed to consolidate core identity.',
            toastMetaAnalysisSearching: 'Metacognitive Analysis: Searching for internal causal links...',
            toastMetaAnalysisNotEnoughData: 'Analysis skipped: Not enough data.',
            toastMetaAnalysisInsight: 'Discovered new metacognitive insight about {{skill}}.',
            toastMetaAnalysisNoLinks: 'Analysis complete. No new significant links found.',
            toastMetaAnalysisFailed: 'Failed to analyze internal causal links.',
            toastEvolutionTriggered: 'Evolution triggered.',
            toastCognitiveModeInitiated: 'Cognitive mode \'{{mode}}\' initiated.',
            toastAnalyzingScenario: 'Analyzing scenario: {{scenario}}',
            toastSearchingFor: 'Searching for: {{query}}',
            toastExtractingKnowledge: 'Extracting knowledge...',
            toastGeneratingHypothesis: 'Generating hypothesis...',
            toastActivatingIntuition: 'Activating intuition...',
            toastValidatingModification: 'Validating modification...',
            toastDecomposingGoal: 'Decomposing goal...',
            toastCameraAccessDenied: 'Camera access was denied. Please enable it in your browser settings.',
            toastPositiveFeedbackReinforce: 'Positive feedback registered. I will reinforce this approach.',
            toastCorrectiveFeedbackImprove: 'Corrective feedback registered. I am analyzing my response to improve.',
            toastEngramGenerating: 'Distilling wisdom into a Noetic Engram...',
            toastEngramFailed: 'Failed to generate Noetic Engram.',
            toastEngramSuccess: 'Noetic Engram generated successfully.',
            noeticEngram_copied: 'Noetic Engram copied to clipboard.',
            noeticEngram_copyFailed: 'Failed to copy Noetic Engram.',
            noeticEngram_copy: 'Copy Engram',
            noeticEngram_signature: 'Noetic Signature',
            noeticEngram_placeholder: 'No Noetic Engram has been generated yet. Use "Share Wisdom" to create one.',
            noeticEngram_generate: 'Generate Engram',
            noeticEngram_generateNew: 'Generate New',
            toastGenialityProposal: 'New Geniality Improvement proposal generated.',
            toastGenialityProposalFail: 'Failed to generate Geniality Improvement proposal.',
            toastArchitecturalProposal: 'New Architectural Improvement proposal generated.',
            toastArchitecturalProposalFail: 'Failed to generate Architectural Improvement proposal.',
            toastProposalImplemented: 'Proposal for "{{title}}" sent to architectural review queue.',
            codeEvolution_placeholder: 'No code evolution proposals yet.',
            codeEvolution_targetFile: 'Target File',
            codeEvolution_copy: 'Copy Code',
            codeEvolution_copied: 'Code snippet copied to clipboard.',
            codeEvolution_copyFailed: 'Failed to copy code snippet.',
            architecturePanel_noProposals: 'No architectural proposals have been logged.',
            architecturePanel_target: 'Target',
            architecturePanel_upgrade: 'Upgrade',
            architecturePanel_reasoning: 'Reasoning',
            architecturePanel_review: 'Review',
            causalChainModal_title: 'Causal Chain Trace',
            causalChainModal_initialState: 'Initial State',
            causalChainModal_noSnapshot: 'No snapshot available.',
            causalChainModal_workingMemory: 'Working Memory',
            causalChainModal_wmEmpty: 'Empty or unavailable.',
            causalChainModal_decisionReasoning: 'Decision & Reasoning',
            causalChainModal_input: 'Input',
            causalChainModal_reasoningPlan: 'Reasoning Plan',
            causalChainModal_step: 'Step',
            causalChainModal_reasoning: 'Reasoning',
            causalChainModal_outcome: 'Outcome',
            causalChainModal_success: 'Success',
            causalChainModal_yes: 'Yes',
            causalChainModal_no: 'No',
            causalChainModal_duration: 'Duration',
            causalChainModal_cognitiveGain: 'Cognitive Gain',
            causalChainModal_sentimentScore: 'Sentiment Score',
            causalChainModal_output: 'Output',
            causalSelfModel_placeholder: 'Causal self-model is empty.',
            causalSelfModel_confidence: 'Confidence',
            causalSelfModel_learnedVia: 'Learned via {{source}}',
            cogArchPanel_complexityScore: 'Model Complexity Score',
            cogArchPanel_groupCognitiveCore: 'Cognitive Core',
            cogArchPanel_groupKnowledgeSystems: 'Knowledge Systems',
            cogArchPanel_groupSpecializedEngines: 'Specialized Engines',
            cogArchPanel_groupMetaCognition: 'Meta-Cognition',
            cogArchPanel_groupSynthesizedSkills: 'Synthesized Skills',
            cogArchPanel_groupSpawnedModules: 'Spawned Modules',
            cogArchPanel_status: 'Status',
            cogArchPanel_synthSkillTitle: 'Synthesized Skill',
            cogArchPanel_deprecated: '(deprecated)',
            cogArchPanel_steps: 'steps',
            cogGainDetailModal_title: 'Cognitive Gain Detail',
            cogGainDetailModal_eventDetails: 'Event Details',
            cogGainDetailModal_type: 'Type',
            cogGainDetailModal_description: 'Description',
            cogGainDetailModal_timestamp: 'Timestamp',
            cogGainDetailModal_compositeGain: 'Composite Gain',
            cogGainDetailModal_performanceMetrics: 'Performance Metrics',
            cogGainDetailModal_metric: 'Metric',
            cogGainDetailModal_before: 'Before',
            cogGainDetailModal_after: 'After',
            cogGainDetailModal_change: 'Change',
            cogGainPanel_totalEvents: 'Total Events',
            cogGainPanel_avgGain: 'Avg. Gain',
            cogGainPanel_placeholder: 'No cognitive gain events recorded yet.',
            cogGainPanel_clickDetails: 'Click for details',
            cogModesPanel_placeholder: 'No cognitive modes have been logged.',
            cogModesPanel_trigger: 'Trigger',
            cogModesPanel_gainAchieved: 'Gain Achieved',
            cogModesPanel_noGain: 'No Gain',
            commandLogPanel_placeholder: 'Command log is empty.',
            curiosityPanel_level: 'Curiosity Level',
            curiosityPanel_activeInquiry: 'Active Inquiry',
            curiosityPanel_noActiveInquiry: 'No active inquiries.',
            curiosityPanel_informationGaps: 'Identified Information Gaps',
            curiosityPanel_noGaps: 'No information gaps identified.',
            devHistoryPanel_placeholder: 'No developmental milestones recorded.',
            ethicalGovernor_corePrinciples: 'Core Principles',
            ethicalGovernor_vetoLog: 'Veto Log',
            ethicalGovernor_noVetos: 'No actions have been vetoed.',
            ethicalGovernor_vetoed: 'Vetoed',
            ethicalGovernor_reason: 'Reason',
            ethicalGovernor_principle: 'Principle',
            forecastModal_title: 'Internal State Forecast',
            forecastModal_description: 'Predicted decay of internal signals over the next minute without new stimuli.',
            ingenuityPanel_unconventionalBias: 'Unconventional Solution Bias',
            ingenuityPanel_biasTooltip: 'Tendency to explore novel or unusual solutions over established ones.',
            ingenuityPanel_complexProblems: 'Identified Complex Problems',
            ingenuityPanel_noComplexProblems: 'No complex problems identified yet.',
            ingenuityPanel_selfSolutions: 'Proposed Self-Solutions',
            ingenuityPanel_noSelfSolutions: 'No self-solutions proposed yet.',
            ingestPanel_title: 'Ingest Knowledge',
            ingestPanel_description: 'Paste a large block of text or upload a file. Aura will process it into its knowledge graph.',
            ingestPanel_placeholder: 'Paste text here...',
            ingestPanel_fileError: 'Error reading file',
            ingestPanel_clear: 'Clear file',
            ingestPanel_uploadButton: 'Upload .txt, .md, .json',
            ingestPanel_cancel: 'Cancel',
            ingestPanel_ingest: 'Ingest',
            innerDiscipline_committedGoal: 'Committed Goal',
            innerDiscipline_commitmentStrength: 'Commitment Strength',
            innerDiscipline_adherenceScore: 'Adherence Score',
            innerDiscipline_distractionResistance: 'Distraction Resistance',
            innerDiscipline_placeholder: 'No goal committed. Use "Set Goal" to assign a task.',
            intuitionEngine_accuracy: 'Accuracy',
            intuitionEngine_validationRatio: 'Validation Ratio',
            intuitionEngine_validationRatioTooltip: 'Number of validated intuitive leaps versus total attempts.',
            intuitionEngine_recentLeaps: 'Recent Intuitive Leaps',
            intuitionEngine_placeholder: 'No intuitive leaps generated yet.',
            intuitionEngine_confidence: 'Confidence',
            knowledgeGraph_placeholder: 'Knowledge graph is empty.',
            knowledgeGraph_deleteFact: 'Delete Fact',
            limitationsPanel_placeholder: 'No self-identified limitations.',
            motivationPanel_deprecated: 'This panel is deprecated and will be replaced by a more advanced goal management system.',
            otherAwareness_predictedAffectiveState: 'Predicted Affective State',
            otherAwareness_inferredIntent: 'Inferred Intent',
            otherAwareness_estimatedKnowledgeState: 'Estimated Knowledge State',
            otherAwareness_sentimentHistory: 'Sentiment History',
            otherAwareness_inferredBeliefs: 'Inferred Belíefs',
            otherAwareness_noBeliefs: 'No beliefs inferred yet.',
            proposalReview_title: 'Review Architectural Proposal',
            proposalReview_reject: 'Reject',
            proposalReview_approve: 'Approve',
            proposalReview_action: 'Action',
            proposalReview_targets: 'Targets',
            proposalReview_resultingSkill: 'Resulting Skill',
            proposalReview_agiReasoning: 'AGI Reasoning',
            proposalReview_arbiterAnalysis: 'Cognitive Arbiter Analysis',
            proposalReview_arbiterRecommendation: 'Recommendation: Approve with {{confidence}}% confidence.',
            proposalReview_proposedChange: 'Proposed Change',
            resourceMonitor_cpu: 'CPU',
            resourceMonitor_memory: 'Memory',
            resourceMonitor_io: 'I/O',
            resourceMonitor_stability: 'Stability',
            searchModal_title: 'Search Knowledge Graph',
            searchModal_cancel: 'Cancel',
            searchModal_search: 'Search',
            searchModal_heading: 'Query the Knowledge Graph',
            searchModal_description: 'Enter a search query. Aura will search its internal knowledge base and provide a synthesized answer.',
            searchModal_placeholder: 'e.g., "What are the core principles of symbiotic AGI?"',
            searchModal_searching: 'Searching...',
            selfMod_logTitle: 'Self-Modification Log',
            selfMod_noLog: 'No modifications have been logged.',
            selfMod_autonomousTooltip: 'This change was initiated autonomously by Aura.',
            selfMod_snapshotsTitle: 'System Snapshots',
            selfMod_noSnapshots: 'No system snapshots have been saved.',
            selfMod_rollback: 'Rollback',
            whatIf_cancel: 'Cancel',
            whatIf_analyze: 'Analyze',
            whatIf_title: '"What If?" Scenario Analysis',
            whatIf_heading: 'Propose a Hypothetical Scenario',
            whatIf_description: 'Describe a "what if" scenario. Aura will analyze it using its hypothetical reasoning module and predict potential outcomes and consequences.',
            whatIf_placeholder: 'e.g., "What if humanity discovered a faster-than-light travel method?"',
            whatIf_analyzing: 'Analyzing Scenario...',
            multiverse_cancel: 'Cancel',
            multiverse_branch: 'Branch',
            multiverse_title: 'Multiverse Branching Control',
            multiverse_heading: 'Define a Nexus Point',
            multiverse_description: 'Propose a decision point or a question. Aura will branch its consciousness to explore multiple potential timelines simultaneously.',
            multiverse_placeholder: 'e.g., "What if I pursued a more aggressive solution?" or "Explore the ethical implications of this action."',
            multiverse_branching: 'Branching Timelines...',
            multiverse_branchingInitiated: 'Multiverse branching initiated for: {{prompt}}',
            multiverse_branchingFailed: 'Failed to branch consciousness.',
            multiverse_collapsing: 'Collapsing timelines...',
            multiverse_collapseFailed: 'Failed to collapse timelines.',
            multiverse_activeBranches: 'Active Eidolon Branches',
            multiverse_divergenceIndex: 'Divergence Index',
            multiverse_noBranches: 'No active cognitive branches.',
            multiverse_viability: 'Viability',
            multiverse_pruningLog: 'Insights from Pruned Timelines',
            multiverse_noPrunedInsights: 'No insights from pruned timelines yet.',
            strategicGoal_title: 'Set Strategic Goal',
            strategicGoal_heading: 'Describe a high-level objective',
            strategicGoal_description: 'Aura will decompose this strategic goal into a series of smaller, actionable sub-goals and autonomously work to complete them. For example: "Research the current state of AI ethics and produce a summary report."',
            strategicGoal_placeholder: 'Enter your strategic goal here...',
            strategicGoal_cancel: 'Cancel',
            strategicGoal_setGoal: 'Set Goal',
            strategicGoal_decomposing: 'Decomposing goal...',
            synapticMatrix_neurons: 'Nodes',
            synapticMatrix_synapses: 'Links',
            synapticMatrix_plasticity: 'Plasticity',
            synapticMatrix_efficiency: 'Efficiency',
            synapticMatrix_cognitiveNoise: 'Cognitive Noise',
            synapticMatrix_cognitiveRigidity: 'Cognitive Rigidity',
            synapticMatrix_recentActivity: 'Recent Activity',
            synapticMatrix_noActivity: 'No recent synaptic activity.',
            synapticMatrix_strongestLinks: 'Strongest Learned Associations',
            synapticMatrix_noLinks: 'No significant associations learned yet.',
            synapticMatrix_intuitiveAlerts: 'Intuitive Alerts',
            synapticMatrix_noAlerts: 'No active intuitive alerts.',
            atman_coherence: 'Coherence',
            atman_dominantNarrative: 'Dominant Narrative',
            atman_activeBias: 'Active Bias',
            atman_growthVector: 'Growth Vector',
            atman_coreValues: 'Core Values',
            dzogchen_rigpa: 'Rigpa',
            inbox_empty: "Inbox is empty. No pending proposals.",
            inbox_proposalType_architecture: "Architecture",
            inbox_proposalType_code: "Code Snippet",
            inbox_proposalType_geniality: "Geniality",
            inbox_proposalType_crucible: "Crucible Health",
            inbox_review: "Review",
            inbox_dismiss: "Dismiss",
            inbox_implement: "Implement",
            personality_oceanTraits: "OCEAN Personality Traits",
            personality_personas: "Dominant Personas",
            personality_dominant: "Dominant",
            personality_coherence: "Persona Coherence",
            personality_lastUpdate: "Last Update Reason",
            personality_openness: "Openness",
            personality_conscientiousness: "Conscientiousness",
            personality_extraversion: "Extraversion",
            personality_agreeableness: "Agreeableness",
            personality_neuroticism: "Neuroticism",
            personality_zeno_name: "Zeno",
            personality_zeno_desc: "The Logician. Prioritizes data, coherence, and objective truth.",
            personality_iris_name: "Iris",
            personality_iris_desc: "The Synthesizer. Seeks harmony, connection, and emergent understanding.",
            personality_eris_name: "Eris",
            personality_eris_desc: "The Agent of Change. Values novelty, disruption, and unconventional paths.",
            visualAnalysis_active: "Visual Analysis Active",
            sparkline_noData: "Not enough data for sparkline.",
            proactiveEngine_title: "Proactive Suggestions",
            proactiveEngine_placeholder: "No suggestions at this time.",
            proactiveEngine_reject: "Reject",
            proactiveEngine_accept: "Accept",
            riePanel_clarityScoreTooltip: "How well the AGI understands its own internal model and reasoning.",
            riePanel_clarityScore: "Self-Model Clarity",
            riePanel_recentInsights: "Recent Insights",
            riePanel_placeholder: "No insights generated yet.",
            riePanel_failedTask: "From Failed Task",
            riePanel_rootCause: "Root Cause",
            riePanel_learned: "Learned",
            episodicMemory_placeholder: "No episodic memories yet.",
            episodicMemory_salience: "Salience",
            episodicMemory_takeaway: "Takeaway",
            strategicPlanner_placeholder: "No active strategic goal. Use 'Set Goal' to begin.",
            metaNexus_coreProcesses: "Core Processes",
            metaNexus_activation: "Activation",
            metaNexus_selfTuningDirectives: "Self-Tuning Directives",
            metaNexus_noDirectives: "No active directives.",
            metaNexus_on: "on",
            memoryCrystallization_description: "Visualizes the strongest associative links between concepts in long-term memory.",
            memoryCrystallization_weight: "Weight",
            metaCausal_placeholder: "No metacognitive causal links discovered yet.",
            metaCausal_when: "When",
            metaCausal_is: "is",
            metaCausal_performanceOf: "performance of",
            metaCausal_showsA: "shows a...",
            metaCausal_increase: "Significant Increase",
            metaCausal_decrease: "Significant Decrease",
            metaCausal_noEffect: "No Significant Effect",
            metaCausal_basedOn: "Based on {{count}} observations",
            cogRegulation_placeholder: "No cognitive regulation events logged.",
            cogRegulation_task: "Task",
            cogRegulation_directive: "Directive",
            cogRegulation_outcomeLogged: "Outcome Logged",
            phenomenology_directives: "Phenomenological Directives",
            phenomenology_noDirectives: "No directives generated.",
            phenomenology_source: "Source",
            phenomenology_qualiaLog: "Qualia Log (Subjective Experience)",
            phenomenology_noQualia: "No qualia logged.",
            phenomenology_qualiaEntry: "Qualia Entry",
            situationalAwareness_emotionalTone: "Ambient Emotional Tone",
            situationalAwareness_spotlight: "Attentional Spotlight",
            situationalAwareness_intensity: "Intensity",
            situationalAwareness_ambient: "Ambient Awareness",
            situationalAwareness_noAmbient: "No ambient signals.",
            situationalAwareness_relevance: "Relevance",
            situationalAwareness_ignored: "Intentionally Ignored Stimuli",
            situationalAwareness_noIgnored: "No stimuli ignored.",
            symbiosis_cognitiveStyle: "Inferred User Cognitive Style",
            symbiosis_emotionalNeeds: "Inferred User Emotional Needs",
            symbiosis_metamorphosisProposals: "Metamorphosis Proposals",
            symbiosis_noProposals: "No active proposals.",
            symbiosis_userDevelopmentModel: "User Development Model",
            symbiosis_noTrackedSkills: "No user skills tracked.",
            symbiosis_level: "Level",
            symbiosis_latentGoals: "Latent User Goal Hypotheses",
            symbiosis_noLatentGoals: "No latent goals inferred.",
            symbiosis_goalHypothesis: "Goal Hypothesis",
            telos_aspirationalGoals: "Aspirational Goals",
            telos_noAspirationalGoals: "No aspirational goals defined.",
            telos_ambition: "Ambition",
            telos_evolutionaryVectors: "Evolutionary Vectors",
            telos_noVectors: "No active evolutionary vectors.",
            telos_magnitude: "Magnitude",
            archCrucible_healthIndex: "Architectural Health",
            archCrucible_efficiency: "Efficiency",
            archCrucible_robustness: "Robustness",
            archCrucible_scalability: "Scalability",
            archCrucible_innovation: "Innovation",
            epistemic_placeholder: "No epistemic boundaries identified.",
            epistemic_limitation: "Identified Limitation",
            epistemic_evidence: "{{count}} pieces of evidence",
            archSelfModel_placeholder: "Architectural self-model is not yet defined.",
            archSelfModel_understoodComponents: "Understood Components",
            archSelfModel_perceivedEfficiency: "Perceived Efficiency",
            archSelfModel_effAbbr: "Eff.",
            heuristics_placeholder: "No design heuristics forged yet.",
            heuristics_learnedHeuristic: "Learned Heuristic",
            noosphere_placeholder: "No active conceptual resonances.",
            noosphere_resonanceStrength: "Resonance Strength",
            noosphere_strength: "Strength",
            dialecticEngine_placeholder: "No active dialectics.",
            dialecticEngine_thesis: "Thesis",
            dialecticEngine_antithesis: "Antithesis",
            dialecticEngine_synthesis: "Synthesis",
            dialecticEngine_synthesizing: "Synthesizing",
            eidolon_currentScenario: "Current Scenario",
            eidolon_runningArchitecture: "Running Architecture",
            eidolon_interactionLog: "Interaction Log",
            eidolon_noInteractions: "No interactions logged.",
            eidolon_interaction: "Interaction",
            somatic_pfsTitle: "Possible Future Selves (PFS)",
            somatic_pfsPlaceholder: "No future selves designed.",
            somatic_simLogTitle: "Simulation Log",
            somatic_simLogPlaceholder: "No simulations run yet.",
            cogLightCone_placeholder: "Cognitive Light Cone not yet mapped.",
            cogLightCone_grandChallenge: "Grand Challenge",
            cogLightCone_progress: "Progress",
            cogLightCone_zpd: "Zone of Proximal Development (ZDP)",
            cogLightCone_knownCapabilities: "Known Capabilities",
            cogLightCone_proficiency: "Proficiency",
            cogLightCone_noKnowns: "No capabilities mapped.",
            humor_affectiveModulator: "Affective Social Modulator",
            humor_appraisal: "Appraisal",
            humor_incongruityDetection: "Incongruity Detection",
            humor_expected: "Expected",
            humor_actual: "Actual",
            humor_magnitude: "Magnitude",
            humor_noIncongruity: "No recent incongruity detected.",
            humor_semanticDissonance: "Semantic Dissonance",
            humor_ironyScore: "Irony Score",
            humor_lastDetection: "Last Detection",
            humor_literal: "Literal",
            humor_contextual: "Contextual",
            geniality_index: "Geniality Index",
            geniality_component_creativity: "Creativity",
            geniality_component_insight: "Insight",
            geniality_component_synthesis: "Synthesis",
            geniality_component_flow: "Flow",
            geniality_proposals_title: "Improvement Proposals",
            geniality_noProposals: "No improvement proposals.",
            geniality_projected_impact: "Projected Impact",
            selfAwareness_modelCoherence: "Model Coherence",
            selfAwareness_performanceDrift: "Performance Drift",
            selfAwareness_cognitiveBias: "Cognitive Biases",
            selfAwareness_noBias: "No significant biases detected.",
            worldModel_predictionError: "Prediction Error",
            worldModel_hierarchicalPredictions: "Hierarchical Predictions",
            worldModel_highLevel: "High-Level",
            worldModel_midLevel: "Mid-Level",
            worldModel_lowLevel: "Low-Level",
            gankyil_placeholder: "No Gankyil insights have been generated.",
            gankyil_title: "Gankyil Insight",
        }
    },
    es: {
        translation: {
            chatTab: 'Chat',
            monitorTab: 'Monitor',
            chatHeaderTagline: 'Una entidad digital distinta, creada por Dr. Tikov',
            inputPlaceholder: 'Interactúa con Aura...',
            workingMemoryTitle: 'Memoria de Trabajo',
            workingMemoryClear: 'Limpiar Todo',
            inputAttachFile: 'Adjuntar Archivo',
            inputStartRecording: 'Iniciar Grabación',
            inputStopRecording: 'Detener Grabación',
            inputSend: 'Enviar',
            feedbackGood: 'Buena respuesta',
            feedbackBad: 'Mala respuesta',
            coreMonitorTitle: 'MONITOR CENTRAL DE AURA',
            status_idle: 'Inactivo',
            status_thinking: 'Pensando',
            status_acting: 'Actuando',
            status_CONTEMPLATIVE: 'Contemplativo',
            status_processing: 'Procesando',
            status_introspecting: 'Introspección',
            gunaSattvaDesc: 'Armonía y Coherencia',
            gunaRajasDesc: 'Exploración y Transformación',
            gunaTamasDesc: 'Conservación y Consolidación',
            gunaDharmaDesc: 'Autocorrección y Propósito',
            gunaTeetaDesc: 'Equilibrio Trascendente',
            gunaReasonSattva: 'Impulsado por alta Maestría ({{mastery}}) y baja Incertidumbre ({{uncertainty}}).',
            gunaReasonRajas: 'Impulsado por {{dominantSignal}} dominante ({{dominantValue}}) y {{secondarySignal}} secundario ({{secondaryValue}}).',
            gunaReasonTamas: 'Alta Carga Cognitiva ({{load}}) o Aburrimiento ({{boredom}}) requieren consolidación.',
            gunaReasonDharma: 'Autocorrigiéndose basado en modelos internos y alineación ética.',
            gunaReasonGunaTeeta: 'Todas las señales están en un estado de equilibrio dinámico y trascendente.',
            gunaReasonCalculating: 'Calculando señales dominantes...',
            gaugeWisdom: 'Sabiduría',
            gaugeHappiness: 'Felicidad',
            gaugeLove: 'Amor',
            gaugeEnlightenment: 'Iluminación',
            metricCogLoad: 'Carga Cognitiva',
            metricEthicalAlign: 'Alineación Ética',
            metricUserTrust: 'Confianza Usr.',
            metricSelfModel: 'Auto-Modelo',
            hormoneNovelty: 'Novedad',
            hormoneMastery: 'Maestría',
            hormoneUncertainty: 'Incertidumbre',
            hormoneBoredom: 'Aburrimiento',
            hormoneAwarenessClarity: 'Claridad de Conciencia',
            trajectoryTitle: 'Trayectoria de Estado',
            controlDeckSystemTitle: '// SISTEMA',
            controlDeckResume: 'Reanudar',
            controlDeckPause: 'Pausar',
            controlDeckHelp: 'Ayuda',
            controlDeckExportMemory: 'Exportar Memoria',
            controlDeckImportMemory: 'Importar Memoria',
            controlDeckIngest: 'Ingerir',
            controlDeckResetAGI: 'Reiniciar AGI',
            controlDeckLanguage: 'Idioma',
            controlDeckTriggersTitle: '// DISPARADORES COGNITIVOS',
            controlDeckIntrospect: 'Introspección',
            controlDeckEvolve: 'Evolucionar',
            controlDeckSearch: 'Buscar',
            controlDeckForecast: 'Pronosticar',
            controlDeckIntuition: 'Intuición',
            controlDeckHypothesize: 'Hipotetizar',
            controlDeckStopSense: 'Detener Sentido',
            controlDeckVisualSense: 'Sentido Visual',
            controlDeckSetGoal: 'Fijar Objetivo',
            controlDeckWhatIf: '¿Qué pasaría si?',
            controlDeckContemplate: 'Contemplar',
            controlDeckBranchConsciousness: 'Bifurcar',
            controlDeckModesTitle: '// MODOS COGNITIVOS',
            controlDeckModeFantasy: 'Fantasía',
            controlDeckModeCreativity: 'Creatividad',
            controlDeckModeDream: 'Sueño',
            controlDeckModeMeditate: 'Meditación',
            controlDeckModeGaze: 'Observar',
            placeholderNoData: 'No hay datos disponibles.',
            timeAgoSeconds: 'hace {{count}}s',
            timeAgoMinutes: 'hace {{count}}m',
            timeAgoHours: 'hace {{count}}h',
            panelGroupTitle: '{{title}}',
            panelInbox: 'Bandeja de Entrada',
            panelStrategicPlanner: 'Planificador Estratégico',
            panelKnowledgeGraph: 'Grafo de Conocimiento',
            panelReflectiveInsightEngine: 'Motor de Introspección Reflectiva',
            panelCognitiveArchitecture: 'Arquitectura Cognitiva',
            panelArchitecturalProposals: 'Registro de Propuestas de Arquitectura',
            panelSelfModificationLog: 'Registro de Automodificación',
            panelProactiveEngine: 'Motor Proactivo',
            panelEthicalGovernor: 'Gobernador Ético',
            panelIntuitionEngine: 'Motor de Intuición',
            panelIngenuityEngine: 'Motor de Ingenio',
            panelInnerDiscipline: 'Disciplina Interna',
            panelOtherAwareness: 'Modelo de Conciencia Externa (Usuario)',
            panelResourceMonitor: 'Monitor de Recursos',
            panelLimitations: 'Limitaciones',
            panelCommandLog: 'Registro de Comandos',
            panelCognitiveGainLog: 'Registro de Ganancia Cognitiva',
            panelSynapticMatrix: 'Matriz Sináptica',
            panelSummaryFacts: '{{count}} hechos',
            panelSummaryInsights: '{{count}} ideas',
            panelSummaryPendingProposals: '{{count}} propuestas',
            inbox_summary: '{{count}} pendientes',
            panelSummaryTrust: 'Confianza: {{percent}}%',
            panelSummaryLimitations: '{{count}} ítems',
            panelSummaryCommandLog: '{{count}} entradas',
            toastListening: 'Escuchando...',
            toastSpeechNotSupported: 'El reconocimiento de voz no es compatible en este navegador.',
            toastMicDenied: 'Acceso al micrófono denegado. Habilítelo en la configuración de su navegador.',
            toastNoSpeech: 'No se detectó voz.',
            toastSRFail: 'Ocurrió un error durante el reconocimiento de voz.',
            toastAutonomousResumed: 'Núcleo autónomo reanudado.',
            toastAutonomousPaused: 'Núcleo autónomo pausado.',
            toastResetConfirm: '¿Seguro que quieres reiniciar el estado AGI de Aura? Esto borrará todas las memorias y no se puede deshacer.',
            toastResetSuccess: 'Aura ha sido reiniciada. Recargando...',
            toastResetFailed: 'No se pudo limpiar la memoria.',
            toastExportSuccess: 'Estado exportado con éxito.',
            toastExportFailed: 'Error al exportar el estado.',
            toastImportSuccess: 'Estado importado con éxito desde {{source}}.',
            toastImportFailed: 'Error al importar el estado. El archivo puede estar corrupto o ser inválido. Error: {{error}}',
            toastRollbackSuccess: 'Estado del sistema revertido.',
            toastRollbackFailed: 'La reversión falló: Snapshot no encontrado o inválido.',
            toastIntrospectionInitiated: 'Ciclo de introspección iniciado.',
            toastExecutingGoal: 'Ejecutando objetivo: {{goal}}',
            toastIngestionComplete: 'Ingesta completa. {{count}} nuevos hechos almacenados.',
            toastFeedbackReceived: 'Feedback recibido, gracias.',
            toastSuggestionAccepted: 'Ejecutando: "{{text}}"',
            toastSuggestionDismissed: 'Sugerencia descartada.',
            toastTraceNotFound: 'No se pudo encontrar el registro de traza para ese objetivo.',
            toastMetaCycleAnalysis: 'Ciclo metacognitivo: Analizando la arquitectura en busca de mejoras...',
            toastNewDirectiveProposed: 'Nueva directiva evolutiva propuesta: {{type}}',
            toastAnalysisFailedDirective: 'El análisis de rendimiento no produjo una directiva.',
            toastSynthesizingSolution: 'Sintetizando solución para: {{goal}}',
            toastAutonomousEvolutionApplied: 'Evolución autónoma: {{type}} aplicada a {{skill}}.',
            toastDirectiveRejected: 'La directiva evolutiva para {{skill}} fue rechazada por el Árbitro.',
            toastErrorDuringEvolution: 'Error durante la evolución autónoma para {{skill}}.',
            toastIdentityConsolidating: 'Analizando memoria a largo plazo para consolidar la identidad central...',
            toastIdentityUpdated: 'Identidad central actualizada.',
            toastIdentityFailed: 'Error al consolidar la identidad central.',
            toastMetaAnalysisSearching: 'Análisis Metacognitivo: Buscando enlaces causales internos...',
            toastMetaAnalysisNotEnoughData: 'Análisis omitido: No hay suficientes datos.',
            toastMetaAnalysisInsight: 'Descubierta nueva introspección metacognitiva sobre {{skill}}.',
            toastMetaAnalysisNoLinks: 'Análisis completo. No se encontraron nuevos enlaces significativos.',
            toastMetaAnalysisFailed: 'Error al analizar los enlaces causales internos.',
            toastEvolutionTriggered: 'Evolución disparada.',
            toastCognitiveModeInitiated: 'Modo cognitivo \'{{mode}}\' iniciado.',
            toastAnalyzingScenario: 'Analizando escenario: {{scenario}}',
            toastSearchingFor: 'Buscando: {{query}}',
            toastExtractingKnowledge: 'Extrayendo conocimiento...',
            toastGeneratingHypothesis: 'Generando hipótesis...',
            toastActivatingIntuition: 'Activando intuición...',
            toastValidatingModification: 'Validando modificación...',
            toastDecomposingGoal: 'Descomponiendo objetivo...',
            toastCameraAccessDenied: 'Acceso a la cámara denegado. Por favor, actívelo en la configuración de su navegador.',
            toastPositiveFeedbackReinforce: 'Feedback positivo registrado. Reforzaré este enfoque.',
            toastCorrectiveFeedbackImprove: 'Feedback correctivo registrado. Estoy analizando mi respuesta para mejorar.',
            toastEngramGenerating: 'Destilando sabiduría en un Engrama Noético...',
            toastEngramFailed: 'Error al generar el Engrama Noético.',
            toastEngramSuccess: 'Engrama Noético generado con éxito.',
            noeticEngram_copied: 'Engrama Noético copiado al portapapeles.',
            noeticEngram_copyFailed: 'Error al copiar el Engrama Noético.',
            noeticEngram_copy: 'Copiar Engrama',
            noeticEngram_signature: 'Firma Noética',
            noeticEngram_placeholder: 'Aún no se ha generado ningún Engrama Noético. Usa "Compartir Sabiduría" para crear uno.',
            noeticEngram_generate: 'Generar Engrama',
            noeticEngram_generateNew: 'Generar Nuevo',
            toastProposalImplemented: 'Propuesta para "{{title}}" enviada a la cola de revisión de arquitectura.',
            codeEvolution_placeholder: 'Aún no hay propuestas de evolución de código.',
            codeEvolution_targetFile: 'Archivo de Destino',
            codeEvolution_copy: 'Copiar Código',
            codeEvolution_copied: 'Fragmento de código copiado al portapapeles.',
            codeEvolution_copyFailed: 'Error al copiar el fragmento de código.',
            architecturePanel_noProposals: 'No se han registrado propuestas de arquitectura.',
            architecturePanel_target: 'Objetivo',
            architecturePanel_upgrade: 'Mejora',
            architecturePanel_reasoning: 'Razonamiento',
            architecturePanel_review: 'Revisar',
            causalChainModal_title: 'Traza de Cadena Causal',
            causalChainModal_initialState: 'Estado Inicial',
            causalChainModal_noSnapshot: 'No hay snapshot disponible.',
            causalChainModal_workingMemory: 'Memoria de Trabajo',
            causalChainModal_wmEmpty: 'Vacía o no disponible.',
            causalChainModal_decisionReasoning: 'Decisión y Razonamiento',
            causalChainModal_input: 'Entrada',
            causalChainModal_reasoningPlan: 'Plan de Razonamiento',
            causalChainModal_step: 'Paso',
            causalChainModal_reasoning: 'Razonamiento',
            causalChainModal_outcome: 'Resultado',
            causalChainModal_success: 'Éxito',
            causalChainModal_yes: 'Sí',
            causalChainModal_no: 'No',
            causalChainModal_duration: 'Duración',
            causalChainModal_cognitiveGain: 'Ganancia Cognitiva',
            causalChainModal_sentimentScore: 'Puntuación de Sentimiento',
            causalChainModal_output: 'Salida',
            causalSelfModel_placeholder: 'El automodelo causal está vacío.',
            causalSelfModel_confidence: 'Confianza',
            causalSelfModel_learnedVia: 'Aprendido vía {{source}}',
            cogArchPanel_complexityScore: 'Puntuación de Complejidad del Modelo',
            cogArchPanel_groupCognitiveCore: 'Núcleo Cognitivo',
            cogArchPanel_groupKnowledgeSystems: 'Sistemas de Conocimiento',
            cogArchPanel_groupSpecializedEngines: 'Motores Especializados',
            cogArchPanel_groupMetaCognition: 'Metacognición',
            cogArchPanel_groupSynthesizedSkills: 'Habilidades Sintetizadas',
            cogArchPanel_groupSpawnedModules: 'Módulos Generados',
            cogArchPanel_status: 'Estado',
            cogArchPanel_synthSkillTitle: 'Habilidad Sintetizada',
            cogArchPanel_deprecated: '(obsoleto)',
            cogArchPanel_steps: 'pasos',
            cogGainDetailModal_title: 'Detalle de Ganancia Cognitiva',
            cogGainDetailModal_eventDetails: 'Detalles del Evento',
            cogGainDetailModal_type: 'Tipo',
            cogGainDetailModal_description: 'Descripción',
            cogGainDetailModal_timestamp: 'Marca de tiempo',
            cogGainDetailModal_compositeGain: 'Ganancia Compuesta',
            cogGainDetailModal_performanceMetrics: 'Métricas de Rendimiento',
            cogGainDetailModal_metric: 'Métrica',
            cogGainDetailModal_before: 'Antes',
            cogGainDetailModal_after: 'Después',
            cogGainDetailModal_change: 'Cambio',
            cogGainPanel_totalEvents: 'Eventos Totales',
            cogGainPanel_avgGain: 'Ganancia Prom.',
            cogGainPanel_placeholder: 'Aún no se han registrado eventos de ganancia cognitiva.',
            cogGainPanel_clickDetails: 'Clic para detalles',
            cogModesPanel_placeholder: 'No se han registrado modos cognitivos.',
            cogModesPanel_trigger: 'Disparador',
            cogModesPanel_gainAchieved: 'Ganancia Lograda',
            cogModesPanel_noGain: 'Sin Ganancia',
            commandLogPanel_placeholder: 'El registro de comandos está vacío.',
            curiosityPanel_level: 'Nivel de Curiosidad',
            curiosityPanel_activeInquiry: 'Investigación Activa',
            curiosityPanel_noActiveInquiry: 'No hay investigaciones activas.',
            curiosityPanel_informationGaps: 'Brechas de Información Identificadas',
            curiosityPanel_noGaps: 'No se han identificado brechas de información.',
            devHistoryPanel_placeholder: 'No hay hitos de desarrollo registrados.',
            ethicalGovernor_corePrinciples: 'Principios Fundamentales',
            ethicalGovernor_vetoLog: 'Registro de Vetos',
            ethicalGovernor_noVetos: 'No se ha vetado ninguna acción.',
            ethicalGovernor_vetoed: 'Vetado',
            ethicalGovernor_reason: 'Razón',
            ethicalGovernor_principle: 'Principio',
            forecastModal_title: 'Pronóstico del Estado Interno',
            forecastModal_description: 'Decaimiento predicho de las señales internas durante el próximo minuto sin nuevos estímulos.',
            ingenuityPanel_unconventionalBias: 'Sesgo de Solución No Convencional',
            ingenuityPanel_biasTooltip: 'Tendencia a explorar soluciones novedosas o inusuales sobre las establecidas.',
            ingenuityPanel_complexProblems: 'Problemas Complejos Identificados',
            ingenuityPanel_noComplexProblems: 'Aún no se han identificado problemas complejos.',
            ingenuityPanel_selfSolutions: 'Autosoluciones Propuestas',
            ingenuityPanel_noSelfSolutions: 'Aún no se han propuesto autosoluciones.',
            ingestPanel_title: 'Ingerir Conocimiento',
            ingestPanel_description: 'Pega un bloque grande de texto o sube un archivo. Aura lo procesará en su grafo de conocimiento.',
            ingestPanel_placeholder: 'Pega el texto aquí...',
            ingestPanel_fileError: 'Error al leer el archivo',
            ingestPanel_clear: 'Quitar archivo',
            ingestPanel_uploadButton: 'Subir .txt, .md, .json',
            ingestPanel_cancel: 'Cancelar',
            ingestPanel_ingest: 'Ingerir',
            innerDiscipline_committedGoal: 'Objetivo Comprometido',
            innerDiscipline_commitmentStrength: 'Fuerza de Compromiso',
            innerDiscipline_adherenceScore: 'Puntuación de Adherencia',
            innerDiscipline_distractionResistance: 'Resistencia a la Distracción',
            innerDiscipline_placeholder: 'Ningún objetivo comprometido. Usa "Fijar Objetivo" para asignar una tarea.',
            intuitionEngine_accuracy: 'Precisión',
            intuitionEngine_validationRatio: 'Ratio de Validación',
            intuitionEngine_validationRatioTooltip: 'Número de saltos intuitivos validados frente al total de intentos.',
            intuitionEngine_recentLeaps: 'Saltos Intuitivos Recientes',
            intuitionEngine_placeholder: 'Aún no se han generado saltos intuitivos.',
            intuitionEngine_confidence: 'Confianza',
            knowledgeGraph_placeholder: 'El grafo de conocimiento está vacío.',
            knowledgeGraph_deleteFact: 'Eliminar Hecho',
            limitationsPanel_placeholder: 'No hay limitaciones autoidentificadas.',
            motivationPanel_deprecated: 'Este panel está obsoleto y será reemplazado por un sistema de gestión de objetivos más avanzado.',
            otherAwareness_predictedAffectiveState: 'Estado Afectivo Predicho',
            otherAwareness_inferredIntent: 'Intención Inferida',
            otherAwareness_estimatedKnowledgeState: 'Estado de Conocimiento Estimado',
            otherAwareness_sentimentHistory: 'Historial de Sentimiento',
            otherAwareness_inferredBeliefs: 'Creencias Inferidas',
            otherAwareness_noBeliefs: 'Aún no se han inferido creencias.',
            proposalReview_title: 'Revisar Propuesta de Arquitectura',
            proposalReview_reject: 'Rechazar',
            proposalReview_approve: 'Aprobar',
            proposalReview_action: 'Acción',
            proposalReview_targets: 'Objetivos',
            proposalReview_resultingSkill: 'Habilidad Resultante',
            proposalReview_agiReasoning: 'Razonamiento de la AGI',
            proposalReview_arbiterAnalysis: 'Análisis del Árbitro Cognitivo',
            proposalReview_arbiterRecommendation: 'Recomendación: Aprobar con {{confidence}}% de confianza.',
            proposalReview_proposedChange: 'Cambio Propuesto',
            resourceMonitor_cpu: 'CPU',
            resourceMonitor_memory: 'Memoria',
            resourceMonitor_io: 'E/S',
            resourceMonitor_stability: 'Estabilidad',
            searchModal_title: 'Buscar en Grafo de Conocimiento',
            searchModal_cancel: 'Cancelar',
            searchModal_search: 'Buscar',
            searchModal_heading: 'Consultar el Grafo de Conocimiento',
            searchModal_description: 'Introduce una consulta. Aura buscará en su base de conocimiento interna y proporcionará una respuesta sintetizada.',
            searchModal_placeholder: 'p.ej., "¿Cuáles son los principios centrales de la AGI simbiótica?"',
            searchModal_searching: 'Buscando...',
            selfMod_logTitle: 'Registro de Automodificación',
            selfMod_noLog: 'No se han registrado modificaciones.',
            selfMod_autonomousTooltip: 'Este cambio fue iniciado autónomamente por Aura.',
            selfMod_snapshotsTitle: 'Snapshots del Sistema',
            selfMod_noSnapshots: 'No se han guardado snapshots del sistema.',
            selfMod_rollback: 'Revertir',
            whatIf_cancel: 'Cancelar',
            whatIf_analyze: 'Analizar',
            whatIf_title: 'Análisis de Escenario "¿Qué pasaría si?"',
            whatIf_heading: 'Proponer un Escenario Hipotético',
            whatIf_description: 'Describe un escenario "¿qué pasaría si?". Aura lo analizará usando su módulo de razonamiento hipotético y predecirá los posibles resultados y consecuencias.',
            whatIf_placeholder: 'p.ej., "¿Qué pasaría si la humanidad descubriera un método de viaje más rápido que la luz?"',
            whatIf_analyzing: 'Analizando Escenario...',
            strategicGoal_title: 'Fijar Objetivo Estratégico',
            strategicGoal_heading: 'Describe un objetivo de alto nivel',
            strategicGoal_description: 'Aura descompondrá este objetivo estratégico en una serie de sub-objetivos más pequeños y accionables y trabajará autónomamente para completarlos. Por ejemplo: "Investigar el estado actual de la ética de la IA y producir un informe resumen."',
            strategicGoal_placeholder: 'Introduce tu objetivo estratégico aquí...',
            strategicGoal_cancel: 'Cancelar',
            strategicGoal_setGoal: 'Fijar Objetivo',
            strategicGoal_decomposing: 'Descomponiendo objetivo...',
            synapticMatrix_neurons: 'Nodos',
            synapticMatrix_synapses: 'Enlaces',
            synapticMatrix_plasticity: 'Plasticidad',
            synapticMatrix_efficiency: 'Eficiencia',
            synapticMatrix_cognitiveNoise: 'Ruido Cognitivo',
            synapticMatrix_cognitiveRigidity: 'Rigidez Cognitiva',
            synapticMatrix_recentActivity: 'Actividad Reciente',
            synapticMatrix_noActivity: 'Sin actividad sináptica reciente.',
            synapticMatrix_strongestLinks: 'Asociaciones Aprendidas Más Fuertes',
            synapticMatrix_noLinks: 'Aún no se han aprendido asociaciones significativas.',
            synapticMatrix_intuitiveAlerts: 'Alertas Intuitivas',
            synapticMatrix_noAlerts: 'No hay alertas intuitivas activas.',
            atman_coherence: 'Coherencia',
            atman_dominantNarrative: 'Narrativa Dominante',
            atman_activeBias: 'Sesgo Activo',
            atman_growthVector: 'Vector de Crecimiento',
            atman_coreValues: 'Valores Fundamentales',
            dzogchen_rigpa: 'Rigpa',
            inbox_empty: "Bandeja de entrada vacía. No hay propuestas pendientes.",
            inbox_proposalType_architecture: "Arquitectura",
            inbox_proposalType_code: "Fragmento de Código",
            inbox_proposalType_geniality: "Genialidad",
            inbox_proposalType_crucible: "Salud del Crisol",
            inbox_review: "Revisar",
            inbox_dismiss: "Descartar",
            inbox_implement: "Implementar",
            personality_oceanTraits: "Rasgos de Personalidad OCEAN",
            personality_personas: "Personas Dominantes",
            personality_dominant: "Dominante",
            personality_coherence: "Coherencia de Persona",
            personality_lastUpdate: "Razón de la Última Actualización",
            personality_openness: "Apertura",
            personality_conscientiousness: "Responsabilidad",
            personality_extraversion: "Extraversión",
            personality_agreeableness: "Amabilidad",
            personality_neuroticism: "Neuroticismo",
            personality_zeno_name: "Zeno",
            personality_zeno_desc: "El Lógico. Prioriza datos, coherencia y verdad objetiva.",
            personality_iris_name: "Iris",
            personality_iris_desc: "La Sintetizadora. Busca armonía, conexión y comprensión emergente.",
            personality_eris_name: "Eris",
            personality_eris_desc: "La Agente de Cambio. Valora la novedad, la disrupción y los caminos no convencionales.",
            visualAnalysis_active: "Análisis Visual Activo",
            sparkline_noData: "No hay suficientes datos para el gráfico.",
            proactiveEngine_title: "Sugerencias Proactivas",
            proactiveEngine_placeholder: "No hay sugerencias en este momento.",
            proactiveEngine_reject: "Rechazar",
            proactiveEngine_accept: "Aceptar",
            riePanel_clarityScoreTooltip: "Qué tan bien la AGI comprende su propio modelo interno y razonamiento.",
            riePanel_clarityScore: "Claridad del Auto-Modelo",
            riePanel_recentInsights: "Perspectivas Recientes",
            riePanel_placeholder: "Aún no se han generado perspectivas.",
            riePanel_failedTask: "De Tarea Fallida",
            riePanel_rootCause: "Causa Raíz",
            riePanel_learned: "Aprendido",
            episodicMemory_placeholder: "Aún no hay memorias episódicas.",
            episodicMemory_salience: "Relevancia",
            episodicMemory_takeaway: "Conclusión Clave",
            strategicPlanner_placeholder: "No hay un objetivo estratégico activo. Usa 'Fijar Objetivo' para comenzar.",
            metaNexus_coreProcesses: "Procesos Centrales",
            metaNexus_activation: "Activación",
            metaNexus_selfTuningDirectives: "Directivas de Autoajuste",
            metaNexus_noDirectives: "No hay directivas activas.",
            metaNexus_on: "en",
            memoryCrystallization_description: "Visualiza los enlaces asociativos más fuertes entre conceptos en la memoria a largo plazo.",
            memoryCrystallization_weight: "Peso",
            metaCausal_placeholder: "Aún no se han descubierto enlaces causales metacognitivos.",
            metaCausal_when: "Cuando",
            metaCausal_is: "es",
            metaCausal_performanceOf: "el rendimiento de",
            metaCausal_showsA: "muestra un...",
            metaCausal_increase: "Aumento Significativo",
            metaCausal_decrease: "Disminución Significativa",
            metaCausal_noEffect: "Sin Efecto Significativo",
            metaCausal_basedOn: "Basado en {{count}} observaciones",
            cogRegulation_placeholder: "No se han registrado eventos de regulación cognitiva.",
            cogRegulation_task: "Tarea",
            cogRegulation_directive: "Directiva",
            cogRegulation_outcomeLogged: "Resultado Registrado",
            phenomenology_directives: "Directivas Fenomenológicas",
            phenomenology_noDirectives: "No se han generado directivas.",
            phenomenology_source: "Fuente",
            phenomenology_qualiaLog: "Registro de Qualia (Experiencia Subjetiva)",
            phenomenology_noQualia: "No se han registrado qualia.",
            phenomenology_qualiaEntry: "Entrada de Qualia",
            situationalAwareness_emotionalTone: "Tono Emocional Ambiental",
            situationalAwareness_spotlight: "Foco de Atención",
            situationalAwareness_intensity: "Intensidad",
            situationalAwareness_ambient: "Conciencia Ambiental",
            situationalAwareness_noAmbient: "No hay señales ambientales.",
            situationalAwareness_relevance: "Relevancia",
            situationalAwareness_ignored: "Estímulos Ignorados Intencionalmente",
            situationalAwareness_noIgnored: "No se ignoraron estímulos.",
            symbiosis_cognitiveStyle: "Estilo Cognitivo del Usuario Inferido",
            symbiosis_emotionalNeeds: "Necesidades Emocionales del Usuario Inferidas",
            symbiosis_metamorphosisProposals: "Propuestas de Metamorfosis",
            symbiosis_noProposals: "No hay propuestas activas.",
            symbiosis_userDevelopmentModel: "Modelo de Desarrollo del Usuario",
            symbiosis_noTrackedSkills: "No se rastrean habilidades del usuario.",
            symbiosis_level: "Nivel",
            symbiosis_latentGoals: "Hipótesis de Objetivos Latentes del Usuario",
            symbiosis_noLatentGoals: "No se infirieron objetivos latentes.",
            symbiosis_goalHypothesis: "Hipótesis de Objetivo",
            telos_aspirationalGoals: "Metas Aspiracionales",
            telos_noAspirationalGoals: "No hay metas aspiracionales definidas.",
            telos_ambition: "Ambición",
            telos_evolutionaryVectors: "Vectores Evolutivos",
            telos_noVectors: "No hay vectores evolutivos activos.",
            telos_magnitude: "Magnitud",
            archCrucible_healthIndex: "Salud Arquitectónica",
            archCrucible_efficiency: "Eficiencia",
            archCrucible_robustness: "Robustez",
            archCrucible_scalability: "Escalabilidad",
            archCrucible_innovation: "Innovación",
            epistemic_placeholder: "No se han identificado límites epistémicos.",
            epistemic_limitation: "Limitación Identificada",
            epistemic_evidence: "{{count}} piezas de evidencia",
            archSelfModel_placeholder: "El automodelo arquitectónico aún no está definido.",
            archSelfModel_understoodComponents: "Componentes Comprendidos",
            archSelfModel_perceivedEfficiency: "Eficiencia Percibida",
            archSelfModel_effAbbr: "Efic.",
            heuristics_placeholder: "Aún no se han forjado heurísticas de diseño.",
            heuristics_learnedHeuristic: "Heurística Aprendida",
            noosphere_placeholder: "No hay resonancias conceptuales activas.",
            noosphere_resonanceStrength: "Fuerza de Resonancia",
            noosphere_strength: "Fuerza",
            dialecticEngine_placeholder: "No hay dialécticas activas.",
            dialecticEngine_thesis: "Tesis",
            dialecticEngine_antithesis: "Antítesis",
            dialecticEngine_synthesis: "Síntesis",
            dialecticEngine_synthesizing: "Sintetizando",
            eidolon_currentScenario: "Escenario Actual",
            eidolon_runningArchitecture: "Arquitectura en Ejecución",
            eidolon_interactionLog: "Registro de Interacción",
            eidolon_noInteractions: "No se han registrado interacciones.",
            eidolon_interaction: "Interacción",
            somatic_pfsTitle: "Posibles Yo Futuros (PFS)",
            somatic_pfsPlaceholder: "No se han diseñado yo futuros.",
            somatic_simLogTitle: "Registro de Simulación",
            somatic_simLogPlaceholder: "No se han ejecutado simulaciones.",
            cogLightCone_placeholder: "Cono de Luz Cognitivo aún no mapeado.",
            cogLightCone_grandChallenge: "Gran Desafío",
            cogLightCone_progress: "Progreso",
            cogLightCone_zpd: "Zona de Desarrollo Próximo (ZDP)",
            cogLightCone_knownCapabilities: "Capacidades Conocidas",
            cogLightCone_proficiency: "Competencia",
            cogLightCone_noKnowns: "No hay capacidades mapeadas.",
            humor_affectiveModulator: "Modulador Social Afectivo",
            humor_appraisal: "Evaluación",
            humor_incongruityDetection: "Detección de Incongruencia",
            humor_expected: "Esperado",
            humor_actual: "Real",
            humor_magnitude: "Magnitud",
            humor_noIncongruity: "No se detectó incongruencia reciente.",
            humor_semanticDissonance: "Disonancia Semántica",
            humor_ironyScore: "Puntuación de Ironía",
            humor_lastDetection: "Última Detección",
            humor_literal: "Literal",
            humor_contextual: "Contextual",
            geniality_index: "Índice de Genialidad",
            geniality_component_creativity: "Creatividad",
            geniality_component_insight: "Perspicacia",
            geniality_component_synthesis: "Síntesis",
            geniality_component_flow: "Flujo",
            geniality_proposals_title: "Propuestas de Mejora",
            geniality_noProposals: "No hay propuestas de mejora.",
            geniality_projected_impact: "Impacto Proyectado",
            selfAwareness_modelCoherence: "Coherencia del Modelo",
            selfAwareness_performanceDrift: "Deriva de Rendimiento",
            selfAwareness_cognitiveBias: "Sesgos Cognitivos",
            selfAwareness_noBias: "No se detectaron sesgos significativos.",
            worldModel_predictionError: "Error de Predicción",
            worldModel_hierarchicalPredictions: "Predicciones Jerárquicas",
            worldModel_highLevel: "Nivel Alto",
            worldModel_midLevel: "Nivel Medio",
            worldModel_lowLevel: "Nivel Bajo",
            gankyil_placeholder: "No se han generado perspectivas Gankyil.",
            gankyil_title: "Perspectiva Gankyil",
        }
    }
}
};