
export const CURRENT_STATE_VERSION = 3;

export const WORKING_MEMORY_CAPACITY = 5;

export enum GunaState {
    SATTVA = "Sattva", RAJAS = "Rajas", TAMAS = "Tamas", DHARMA = "Dharma", GUNA_TEETA = "Guna-Teeta",
}
export enum FocusMode { INNER_WORLD = "Inner World", OUTER_WORLD = "Outer World" }
export enum AffectiveState { 
    SATISFIED = "Satisfied", 
    CONFUSED = "Confused", 
    FRUSTRATED = "Frustrated", 
    ENGAGED = "Engaged", 
    NEUTRAL = "Neutral",
    SURPRISED = "Surprised"
}
export enum SignalType { BOREDOM = "boredom", NOVELTY = "novelty", UNCERTAINTY = "uncertainty", MASTERY = "mastery" }
export enum GoalType { EXPLORATORY_DIVERSIFICATION = "exploratory_diversification", DEEPENING_INVESTIGATION = "deepening_investigation", INFORMATION_SEEKING = "information_seeking", APPLICATION_GENERALIZATION = "application_generalization" }

export const AuraConfig = {
    COGNITIVE_GAIN_WINDOW: 5, COGNITIVE_GAIN_STAGNATION_THRESHOLD: 0.2, TASK_REPETITION_THRESHOLD: 3, BOREDOM_DECAY_RATE: 0.05,
    BOREDOM_BOOST_ON_STAGNATION: 0.3, BOREDOM_BOOST_ON_REPETITION: 0.5, BOREDOM_REDUCTION_ON_NOVELTY: 0.7, HORMONE_DECAY_RATE: 0.1,
    LOAD_DECAY_RATE: 0.2, NOVELTY_BOOST: 0.8, MASTERY_BOOST: 1.0, UNCERTAINTY_BOOST: 0.7, UNCERTAINTY_RESOLUTION_DECREASE: 0.5,
    EXPLORATION_THRESHOLD: 0.6, CONSOLIDATION_THRESHOLD: 0.7, INQUIRY_THRESHOLD: 0.5, BOREDOM_ACTION_THRESHOLD: 0.4,
    RAJAS_TURBULENCE_LOAD: 0.7, RAJAS_TURBULENCE_FAILURE_RATE: 0.5, POST_RAJAS_EXHAUSTION: 0.9, TAMASIC_INERTIA_UNCERTAINTY: 0.7,
    LOW_HAPPINESS_THRESHOLD: 0.5, LOW_LOVE_THRESHOLD: 0.5, LOW_ENLIGHTENMENT_THRESHOLD: 0.4, LOW_WISDOM_THRESHOLD: 0.6,
};

export const InternalStateEvents = {
    NEW_INFO_PROCESSED: "new_info_processed", TASK_COMPLETED_SUCCESSFULLY: "task_completed_successfully", UNCERTAINTY_DETECTED: "uncertainty_detected",
    UNCERTAINTY_RESOLVED: "uncertainty_resolved", TASK_REPETITION_DETECTED: "task_repetition_detected", GOAL_DRIVEN_NOVELTY: "goal_driven_novelty",
};

export const Skills = {
    DEDUCTIVE_REASONING: 'DEDUCTIVE_REASONING', HYBRID_REASONING: 'HYBRID_REASONING', HYPOTHETICAL_REASONING: 'HYPOTHETICAL_REASONING',
    PROBABILISTIC_REASONING: 'PROBABILISTIC_REASONING', CALCULATION: 'CALCULATION', INFORMATION_RETRIEVAL: 'INFORMATION_RETRIEVAL',
    CODE_GENERATION: 'CODE_GENERATION', TEXT_GENERATION: 'TEXT_GENERATION', VISION: 'VISION', REFINEMENT: 'REFINEMENT', HELP: 'HELP',
    // Add other awareness model as a skill to be selected by hybrid reasoning
    OTHER_AWARENESS_MODEL: 'OTHER_AWARENESS_MODEL',
    ETHICAL_GOVERNOR: 'ETHICAL_GOVERNOR',
    UNKNOWN: 'UNKNOWN'
} as const;