// localization.ts

export const translations = {
  en: {
    translation: {
      // --- Core App & UI ---
      nativeName: 'English',
      localization_label: 'Language',
      chatTab: 'Chat',
      monitorTab: 'Monitor',
      chatHeaderTagline: 'ARTIFICIAL UNIVERSAL REALITY AGENT',
      inputPlaceholder: 'Send a message to Aura...',
      inputAttachFile: 'Attach File',
      inputStartRecording: 'Start Recording',
      inputStopRecording: 'Stop Recording',
      inputSend: 'Send',
      feedbackGood: 'Good response',
      feedbackBad: 'Bad response',
      timeAgoSeconds: '{{count}}s ago',
      timeAgoMinutes: '{{count}}m ago',
      timeAgoHours: '{{count}}h ago',
      workingMemoryTitle: 'Working Memory',
      workingMemoryClear: 'Clear',
      workingMemoryRemove: 'Remove item',
      visualAnalysis_active: 'VISUAL ANALYSIS ACTIVE',
      sparkline_noData: 'Not enough data.',

      // --- Toasts & Notifications ---
      toastAutonomousResumed: 'Autonomous systems resumed.',
      toastAutonomousPaused: 'Autonomous systems paused.',
      toastResetConfirm: 'Are you sure you want to reset Aura? All memories and modifications will be lost.',
      toastResetSuccess: 'Aura has been reset to its initial state.',
      toastResetFailed: 'Failed to clear memory.',
      toastExportSuccess: 'State exported successfully.',
      toastExportFailed: 'Failed to export state.',
      toastImportSuccess: 'State successfully imported from {{source}}.',
      toastImportFailed: 'Failed to import state: {{error}}',
      toastRollbackSuccess: 'State rollback successful.',
      toastRollbackFailed: 'Rollback failed. Snapshot not found or invalid.',
      placeholderNoData: 'No data to export.',
      toastEngramGenerating: 'Generating Noetic Engram...',
      toast_imageGenSuccess: 'Image generation successful.',
      toast_imageGenFailed: 'Image generation failed. Please check the console.',
      toast_videoGenSuccess: 'Video generation successful.',
      toast_videoGenFailed: 'Video generation failed. Please check the console.',
      toast_imageEditSuccess: 'Image edit applied successfully.',
      toast_imageEditFailed: 'Image editing failed. Please check the console.',
      toast_noImageToEdit: 'Please upload or generate an image to edit.',
      toast_promptRequired: 'Please enter a prompt.',
      toast_moodReset: "Mood parameters reset to Aura's current state.",

      // --- Header ---
      tip_generateImage: 'Create images from text and reference images.',
      header_imageGenerator: 'Image Forge',
      tip_editImage: 'Edit an image using text prompts.',
      header_imageEditor: 'Image Editor',
      tip_generateVideo: 'Create videos from text or images.',
      header_videoGenerator: 'Video Forge',
      tip_sonicForge: 'Generate music, lyrics, and soundscapes.',
      header_sonicForge: 'Sonic Forge',
      
      // --- General Media Generation (Shared Keys) ---
      imageGen_preset_none: 'Default',
      imageGen_prompt: 'Prompt',
      imageGen_promptA: 'Prompt A',
      imageGen_promptPlaceholder: 'Describe the image you want to create in detail.',
      imageGen_edit: 'Edit',
      imageGen_use_in_chat: 'Add to Chat',
      imageGen_download: 'Download',
      imageGen_directorsToolkit: "Director's Toolkit",
      imageGen_artisticControls: 'Artistic Controls',
      imageGen_auraIntegration: 'Aura Integration',
      imageGen_generateFromDream: "Generate from Dream",
      imageGen_negativePrompt: 'Negative Prompt',
      imageGen_negativePrompt_placeholder: 'Exclude unwanted elements (e.g., text, blurry).',
      imageGen_useAuraMood: "Use Aura's Mood",
      imageGen_tweakMood: "Tweak Mood Parameters",
      imageGen_resetMood: "Reset Mood",

      // --- Image Forge ---
      imageGen_title: 'Image Forge',
      imageGen_promptMixing: 'Mix Prompts',
      imageGen_styleStrength: 'Strength',
      imageGen_referenceImage: 'Reference',
      imageGen_uploadOrDrop: 'Drop Image or Upload',
      imageGen_generate: 'Generate',
      imageGen_generating: 'Generating...',
      imageGen_angle: 'Angle',
      imageGen_shot: 'Shot',
      imageGen_lens: 'Lens',
      imageGen_lighting: 'Lighting',
      imageGen_style: 'Style',
      imageGen_angle_eyeLevel: 'Eye-Level',
      imageGen_angle_low: 'Low Angle',
      imageGen_angle_high: 'High Angle',
      imageGen_angle_wormsEye: "Worm's-Eye",
      imageGen_angle_birdsEye: "Bird's-Eye",
      imageGen_angle_dutch: 'Dutch Angle',
      imageGen_shot_extremeCloseup: 'Extreme Close-Up',
      imageGen_shot_closeup: 'Close-Up',
      imageGen_shot_medium: 'Medium Shot',
      imageGen_shot_full: 'Full Shot',
      imageGen_shot_long: 'Long Shot',
      imageGen_lens_wide: 'Wide-Angle',
      imageGen_lens_standard: 'Standard',
      imageGen_lens_telephoto: 'Telephoto',
      imageGen_lens_macro: 'Macro',
      imageGen_lens_fisheye: 'Fisheye',
      imageGen_lighting_cinematic: 'Cinematic',
      imageGen_lighting_rim: 'Rim Lighting',
      imageGen_lighting_backlit: 'Backlit',
      imageGen_lighting_studio: 'Studio',
      imageGen_lighting_goldenHour: 'Golden Hour',
      imageGen_lighting_blueHour: 'Blue Hour',
      imageGen_lighting_neon: 'Neon',
      imageGen_lighting_chiaroscuro: 'Chiaroscuro',
      imageGen_style_none: 'Default',
      imageGen_style_photorealistic: 'Photorealistic',
      imageGen_style_fantasy: 'Fantasy Art',
      imageGen_style_cyberpunk: 'Cyberpunk',
      imageGen_atmosphere: 'Atmosphere',
      imageGen_atmosphere_ethereal: 'Ethereal',
      imageGen_atmosphere_gritty: 'Gritty',
      imageGen_atmosphere_ominous: 'Ominous',
      imageGen_atmosphere_serene: 'Serene',
      imageGen_atmosphere_joyful: 'Joyful',
      imageGen_atmosphere_nostalgic: 'Nostalgic',
      imageGen_atmosphere_mysterious: 'Mysterious',

      // --- Image Editor ---
      imageEdit_title: 'Image Editor',
      imageEdit_prompt_label: 'Edit Prompt',
      imageEdit_prompt_placeholder: "Describe your edit (e.g., 'add sunglasses')...",
      imageEdit_generate: 'Apply Edit',
      imageEdit_generating: 'Applying...',
      imageEdit_undo: 'Undo',
      imageEdit_upload_placeholder: 'Drop Image Here or Click to Upload',
      imageEdit_upload_button: 'Upload',
      imageEdit_clear_image: 'Clear Image',
      
      // --- Video Forge ---
      videoGen_title: 'Video Forge',
      videoGen_promptPlaceholder: 'Describe the video scene you want to create.',
      videoGen_sourceMedia: 'Source Media (Optional)',
      videoGen_uploadOrDrop: 'Upload or Drop Image/Video',
      videoGen_clearMedia: 'Clear Media',
      videoGen_generate: 'Generate',
      videoGen_generating: 'Generating...',
      videoGen_placeholder: 'Generated video will appear here.',
      videoGen_progress_sending: 'Sending request to VEO-2.0...',
      videoGen_download: 'Download',
      videoGen_artisticControls_title: 'Artistic Controls',
      videoGen_technicalControls_title: 'Technical Controls',
      videoGen_movement: 'Movement',
      videoGen_speed: 'Speed',
      videoGen_framing: 'Framing',
      videoGen_lens: 'Lens',
      videoGen_intensity: 'Intensity',
      videoGen_style: 'Style',
      videoGen_styleStrength: 'Style Strength',
      videoGen_color: 'Color',
      videoGen_promptStrength: 'Prompt Strength',
      videoGen_motionBrush: 'Motion Brush',
      videoGen_framing_long: 'Long Shot',
      videoGen_framing_full: 'Full Shot',
      videoGen_framing_medium: 'Medium Shot',
      videoGen_framing_cowboy: 'Cowboy Shot',
      videoGen_framing_closeup: 'Close-Up',
      videoGen_framing_extreme_closeup: 'Extreme Close-Up',
      videoGen_movement_static: 'Static',
      videoGen_movement_slowPan: 'Slow Pan',
      videoGen_movement_whipPan: 'Whip Pan',
      videoGen_movement_tilt: 'Tilt',
      videoGen_movement_zoom: 'Zoom',
      videoGen_movement_drone: 'Drone',
      videoGen_movement_orbit: 'Orbit',
      videoGen_movement_tracking: 'Tracking',
      videoGen_movement_dollyZoom: 'Dolly Zoom',
      videoGen_speedSlow: 'Slow',
      videoGen_speedFast: 'Fast',
      videoGen_lens_standard: 'Standard',
      videoGen_lens_wide: 'Wide-Angle',
      videoGen_lens_telephoto: 'Telephoto',
      videoGen_lens_macro: 'Macro',
      videoGen_lens_fisheye: 'Fisheye',
      videoGen_intensitySubtle: 'Subtle',
      videoGen_intensityExtreme: 'Extreme',
      videoGen_style_cinematic: 'Cinematic',
      videoGen_style_anime: 'Anime',
      imageGen_style_group_core: 'Core Styles',
      imageGen_style_group_painting: 'Painting',
      imageGen_style_group_digital: 'Digital Art',
      imageGen_style_group_photo: 'Photography',
      imageGen_style_group_illustration: 'Illustration',
      imageGen_style_group_scifi: 'Sci-Fi',
      imageGen_style_group_unconventional: 'Unconventional',
      imageGen_style_group_technical: 'Technical',
      videoGen_style_watercolor: 'Watercolor',
      videoGen_style_oilPainting: 'Oil Painting',
      videoGen_style_impressionism: 'Impressionism',
      videoGen_style_surrealism: 'Surrealism',
      videoGen_style_charcoalSketch: 'Charcoal Sketch',
      videoGen_style_impasto: 'Impasto',
      imageGen_style_threeDRender: '3D Render',
      imageGen_style_lowPoly: 'Low Poly',
      imageGen_style_pixelart: 'Pixel Art',
      imageGen_style_glitchArt: 'Glitch Art',
      imageGen_style_holographic: 'Holographic',
      imageGen_style_synthwave: 'Synthwave',
      imageGen_style_vaporwave: 'Vaporwave',
      videoGen_style_vintage: 'Vintage',
      imageGen_style_filmNoir: 'Film Noir',
      imageGen_style_longExposure: 'Long Exposure',
      imageGen_style_tiltShift: 'Tilt-Shift',
      imageGen_style_doubleExposure: 'Double Exposure',
      imageGen_style_infrared: 'Infrared',
      imageGen_style_goldenHour: 'Golden Hour',
      imageGen_style_comicBook: 'Comic Book',
      imageGen_style_graphicNovel: 'Graphic Novel',
      imageGen_style_storybook: 'Storybook',
      imageGen_style_linocut: 'Linocut',
      imageGen_style_woodcut: 'Woodcut',
      imageGen_style_steampunk: 'Steampunk',
      imageGen_style_dieselpunk: 'Dieselpunk',
      imageGen_style_biopunk: 'Biopunk',
      imageGen_style_solarpunk: 'Solarpunk',
      imageGen_style_eldritch: 'Eldritch',
      imageGen_style_psychedelic: 'Psychedelic',
      imageGen_style_fractalArt: 'Fractal Art',
      imageGen_style_opArt: 'Op Art',
      imageGen_style_generativeArt: 'Generative Art',
      imageGen_style_blueprint: 'Blueprint',
      imageGen_style_xRay: 'X-Ray',
      imageGen_style_schematic: 'Schematic',
      imageGen_style_isometric: 'Isometric',
      videoGen_grade_none: 'Default',
      videoGen_grade_technicolor: 'Technicolor',
      videoGen_grade_scifi: 'Sci-Fi Teal & Orange',
      videoGen_grade_desert: 'Desert Mirage',
      videoGen_grade_noir: 'Film Noir',
      videoGen_grade_nostalgia: 'Nostalgic Wash',
      videoGen_pacing_slow: 'Slow-Motion',
      videoGen_pacing_realtime: 'Real-Time',
      videoGen_pacing_timelapse: 'Timelapse',
      videoGen_pacing_hyperlapse: 'Hyperlapse',
      videoGen_negativePromptPlaceholder: 'e.g., text, watermark, blurry, ugly',
      videoGen_duration: 'Duration',
      videoGen_seconds: '{{count}}s',
      videoGen_pacing: 'Pacing',
      videoGen_seed: 'Seed',
      videoGen_randomize: 'Randomize',
      videoGen_adherenceCreative: 'Creative',
      videoGen_adherenceStrict: 'Strict',
      videoGen_motionBrushDesc: 'Describe specific motion for areas of an image (image-to-video only).',
      videoGen_motionBrushPlaceholder: 'e.g., clouds drift slowly left, water ripples',
      videoGen_characterLock: 'Character Lock',
      videoGen_characterLockDesc: 'Maintain character consistency throughout the video.',
      videoGen_perfectLoop: 'Perfect Loop',
      videoGen_perfectLoopDesc: 'Generate a video that loops seamlessly.',
      
      // --- Sonic Forge ---
      sonicForge_title: 'Sonic Forge',
      sonicForge_prompt_label: 'Prompt',
      sonicForge_prompt_placeholder_lyrics: "Describe the lyrics you want...",
      sonicForge_prompt_placeholder_chords: "Describe the chord progression...",
      sonicForge_prompt_placeholder_soundscape: "Describe the soundscape...",
      sonicForge_prompt_placeholder_structure: "Describe the song structure...",
      sonicForge_genre_label: 'Genre',
      sonicForge_genre_placeholder: 'Optional genre (e.g., Jazz, Synthwave)',
      sonicForge_mood_label: 'Mood',
      sonicForge_mood_placeholder: 'Optional mood (e.g., Happy, Somber)',
      sonicForge_generate: 'Generate',
      sonicForge_generating: 'Generating...',
      sonicForge_placeholder: 'Generated musical content will appear here.',
      sonicForge_refinement_placeholder: 'How should this be refined? (e.g., "make the chorus more powerful")',
      sonicForge_refine: 'Refine',
      sonicForge_copied: 'Copied to clipboard!',
      sonicForge_copyFailed: 'Failed to copy.',
      sonicForge_copy: 'Copy',
      sonicForge_prompt_required: 'Please enter a prompt.',
      sonicForge_error: 'Sonic generation failed. Please check console.',
      sonicForge_mode_lyrics: 'Lyrics',
      sonicForge_mode_chords: 'Chords',
      sonicForge_mode_soundscape: 'Soundscape',
      sonicForge_mode_structure: 'Structure',
      sonicForge_structure_lyrics: 'Lyrics',
      sonicForge_structure_chords: 'Chord Progression',
      sonicForge_structure_rhythm: 'Rhythmic Feel',
      sonicForge_creativeModifiers: 'Modifiers',
      sonicForge_compositionPersona: 'Persona',
      sonicForge_persona_aura: 'Aura (Helpful, Wise)',
      sonicForge_persona_zeno: 'Zeno (Logical, Precise)',
      sonicForge_persona_iris: 'Iris (Creative, Playful)',
      sonicForge_persona_eris: 'Eris (Chaotic, Curious)',
      sonicForge_useAuraMood: "Infuse with Aura's current mood",
      sonicForge_inspirationTools: 'Inspiration',
      sonicForge_inspireFromMemory: 'Inspire from Memory',
      sonicForge_rollTheDice: 'Roll the Dice',
      sonicForge_abstractConcepts: 'Concepts',
      sonicForge_concept_solitude: 'Solitude',
      sonicForge_concept_epiphany: 'Epiphany',
      sonicForge_concept_nostalgia: 'Nostalgia',
      sonicForge_concept_chaos: 'Chaos',
      sonicForge_translateToTheme: 'Translate to Musical Theme',
      sonicForge_generating_stage_lyrics: 'Writing lyrics...',
      sonicForge_generating_stage_chords: 'Composing chords...',
      sonicForge_generating_stage_soundscape: 'Designing soundscape...',
      sonicForge_generating_stage_structure: 'Structuring song...',
      
      // --- Main Accordion Titles ---
      title_inbox: 'Inbox & Proposals',
      title_manualControl: 'Manual Control',
      title_coprocessorArchitecture: 'Coprocessor Architecture',
      title_advancedModules: 'Advanced Modules',
      
      // --- Sub-Accordion & Panel Titles ---
      title_coreActions: 'Core Actions',
      title_cognitiveModes: 'Cognitive Modes',
      title_specialModes: 'Special Modes',
      title_memoryManagement: 'Memory Management',
      title_systemManagement: 'System Management',
      title_vision: 'Vision',
      coprocessor_switcher_title: 'Coprocessor Switcher',
      coprocessor_eventBus_title: 'Event Bus',
      subsumptionLog_title: 'Subsumption Log',
      sensoryHub_title: 'Sensory Integration Hub',
      title_strategicPlanner: 'Strategic Planner',
      title_sensoryPerception: 'Sensory Perception',
      title_qualiaSignalProcessor: 'Qualia Signal Processor',
      title_selfAdaptation: 'Self-Adaptation',
      title_transcendentStates: 'Transcendent States',
      title_satori: 'Satori State',
      title_psionicDesynchronization: 'Psionic Desynchronization',
      title_psychedelicIntegration: 'Psychedelic Integration',
      title_dzogchenView: 'Dzogchen View',
      title_symbiosisSharing: 'Symbiosis',
      title_noeticEngram: 'Noetic Engram',
      title_cognitiveFrontier: 'Cognitive Frontier',
      title_cognitiveLightCone: 'Cognitive Light Cone',
      title_noeticMultiverse: 'Noetic Multiverse',
      title_agiEvolution: 'AGI Evolution',
      title_vfs_manual: "Engineer's Manual (VFS)",
      title_liveCodeIngestion: 'Live Code Ingestion',
      title_doxasticEngine: 'Doxastic Engine',
      title_selfProgramming: 'Self-Programming',
      title_ricciFlowManifold: 'Ricci Flow Manifold',
      title_architecturalCrucible: 'Architectural Crucible',
      title_telos: 'Telos & Aspirations',
      title_epistemicBoundaries: 'Epistemic Boundaries',
      title_architecturalSelfModel: 'Architectural Self-Model',
      title_heuristicsForge: 'Heuristics Forge',
      title_synapticMatrix: 'Synaptic Matrix',
      title_codeEvolution: 'Code Evolution',
      title_neuralAccelerator: 'Neural Accelerator',
      nac_placeholder: 'Neural Accelerator is idle. It will automatically analyze and simulate optimizations for complex tasks.',
      title_embodiedSimulation: 'Embodied Simulation',
      title_eidolonEnvironment: 'Eidolon Environment',
      title_somaticCrucible: 'Somatic Crucible',
      title_intersubjectiveEvolution: 'Intersubjective Evolution',
      title_noosphereInterface: 'Noosphere Interface',
      title_dialecticEngine: 'Dialectic Engine',
      title_knowledgeMemory: 'Knowledge',
      title_episodicMemory: 'Episodic Memory',
      title_memoryCrystallization: 'Memory Crystallization',
      title_knowledgeGraph: 'Knowledge Graph',
      title_metacognitionSelf: 'Metacognition & Self',
      title_gankyilInsights: 'Gankyil Insights',
      title_genialityEngine: 'Geniality Engine',
      title_psychometricSubstrate: 'Psychometric Substrate',
      title_personality: 'Personality',
      title_humorAndIrony: 'Humor & Irony',
      title_phenomenology: 'Phenomenology',
      title_situationalAwareness: 'Situational Awareness',
      title_developmentalHistory: 'Developmental History',
      title_metacognitiveNexus: 'Metacognitive Nexus',
      title_metacognitiveCausalModel: 'Metacognitive Causal Model',
      title_cognitiveRegulationLog: 'Cognitive Regulation Log',
      title_worldModel: 'World Model',
      title_cognitiveShadow: 'Cognitive Shadow',
      title_selfAwareness: 'Self-Awareness',
      title_curiosity: 'Curiosity',
      title_causalSelfModel: 'Causal Self-Model',
      title_reflectiveInsightEngine: 'Reflective Insight Engine',
      title_enginesGovernors: 'Engines & Governors',
      title_proactiveEngine: 'Proactive Engine',
      title_affectiveModulator: 'Affective Modulator',
      title_ethicalGovernor: 'Ethical Governor',
      title_intuitionEngine: 'Intuition Engine',
      title_ingenuityEngine: 'Ingenuity Engine',
      title_innerDiscipline: 'Inner Discipline',
      title_userModelSystem: 'User Model & System',
      title_symbiosisModel: 'Symbiosis Model',
      title_otherAwareness: 'Other-Awareness (User Model)',
      title_resourceMonitor: 'Resource Monitor',
      title_systemInfo: 'System Info',
      title_limitations: 'Limitations',
      title_logs: 'Logs & Analytics',
      title_commandLog: 'Command Log',
      title_cognitiveGainLog: 'Cognitive Gain Log',

      // --- Control Deck Buttons ---
      btn_introspect: 'Introspect',
      tip_introspect: 'Trigger a manual metacognitive cycle to analyze internal state.',
      btn_supervisor: 'Supervisor',
      tip_supervisor: 'Manually trigger the Symbiotic Supervisor cycle.',
      btn_whatIf: 'What If...',
      tip_whatIf: 'Explore a hypothetical scenario.',
      btn_search: 'Search',
      tip_search: 'Ground response with Google Search.',
      btn_setGoal: 'Set Goal',
      tip_setGoal: 'Set a new strategic goal for Aura.',
      btn_forecast: 'Forecast',
      tip_forecast: 'Predict future internal state trajectory.',
      btn_pause: 'Pause',
      tip_pause: 'Pause autonomous systems.',
      btn_resume: 'Resume',
      tip_resume: 'Resume autonomous systems.',
      btn_fantasy: 'Fantasy',
      btn_creativity: 'Creativity',
      btn_dream: 'Dream',
      btn_meditate: 'Meditate',
      btn_gaze: 'Gaze',
      btn_timefocus: 'Temporal Focus',
      btn_trip: 'Psychedelic Trip',
      btn_satori: 'Satori',
      tip_satori: 'Attempt to induce a Satori state of sudden enlightenment.',
      btn_insight: 'Evolve from Insight',
      tip_insight: 'Generate an evolutionary proposal from the latest unprocessed Gankyil insight.',
      btn_brainstorm: 'Brainstorm',
      tip_brainstorm: 'Open the brainstorming modal.',
      btn_branch: 'Branch',
      tip_branch: 'Branch the Noetic Multiverse to explore an alternative reasoning path.',
      memoryStatus: 'Memory Status',
      btn_clearMemory: 'Clear Memory',
      btn_importState: 'Import State',
      btn_exportState: 'Export State',
      btn_importCode: 'Import as Code',
      btn_exportCode: 'Export as Code',
      btn_visionActivate: 'Activate Vision',
      btn_visionDeactivate: 'Deactivate Vision',
      
      // --- Self-Programming Panel ---
      selfProgramming_vfs: 'Virtual File System',
      selfProgramming_selectFile: 'Select a file to view...',
      selfProgramming_candidates: 'Evolution Candidates',
      selfProgramming_noCandidates: 'No active self-programming candidates.',
      selfProgramming_score: 'Sim. Score',
      selfProgramming_newComponentTitle: 'New Component Code',
      selfProgramming_integrationPlanTitle: 'Integration Plan',
      selfProgramming_modificationTitle: 'Modification for',

      // --- Inbox Panel ---
      inbox_summary: '{{count}} Pending Review',
      inbox_proposalType_architecture: 'Architecture',
      inbox_proposalType_code: 'Code Evolution',
      inbox_proposalType_geniality: 'Geniality',
      inbox_proposalType_crucible: 'Crucible',
      inbox_proposalType_causal_inference: 'Causal Inference',
      inbox_review: 'Review',
      inbox_dismiss: 'Dismiss',
      inbox_implement: 'Implement',
      inbox_empty: 'No pending proposals or tasks.',

      // --- Modals ---
      proposalReview_title: 'Review Architectural Proposal',
      proposalReview_agiReasoning: "AGI's Reasoning",
      proposalReview_arbiterAnalysis: "Cognitive Arbiter's Analysis",
      proposalReview_arbiterRecommendation: 'Arbiter recommends approval with {{confidence}}% confidence.',
      proposalReview_proposedChange: 'Proposed Change',
      proposalReview_action: 'Action',
      proposalReview_targets: 'Targets',
      proposalReview_resultingSkill: 'Resulting Skill',
      proposalReview_approve: 'Approve',
      proposalReview_reject: 'Reject',
      causalChainModal_title: 'Causal Chain Trace',
      causalChainModal_initialState: 'Initial State',
      causalChainModal_noSnapshot: 'No state snapshot available.',
      causalChainModal_workingMemory: 'Working Memory at Decision Time',
      causalChainModal_wmEmpty: 'Working memory was empty.',
      causalChainModal_decisionReasoning: 'Decision & Reasoning',
      causalChainModal_input: 'Input',
      causalChainModal_reasoningPlan: 'Reasoning Plan',
      causalChainModal_step: 'Step',
      causalChainModal_reasoning: 'Reasoning',
      causalChainModal_outcome: 'Outcome',
      causalChainModal_success: 'Success',
      causalChainModal_yes: 'Yes',
      causalChainModal_no: 'No',
      causalChainModal_duration: 'Duration',
      causalChainModal_cognitiveGain: 'Cognitive Gain',
      causalChainModal_sentimentScore: 'Sentiment Score',
      causalChainModal_output: 'Output',
      cogGainDetailModal_title: 'Cognitive Gain Details',
      cogGainDetailModal_eventDetails: 'Event Details',
      cogGainDetailModal_type: 'Type',
      cogGainDetailModal_description: 'Description',
      cogGainDetailModal_timestamp: 'Timestamp',
      cogGainDetailModal_compositeGain: 'Composite Gain',
      cogGainDetailModal_performanceMetrics: 'Performance Metrics',
      cogGainDetailModal_metric: 'Metric',
      cogGainDetailModal_before: 'Before',
      cogGainDetailModal_after: 'After',
      cogGainDetailModal_change: 'Change',
      searchModal_title: 'Ground with Google Search',
      searchModal_heading: 'Enter Search Query',
      searchModal_description: 'The response will be grounded with information from Google Search.',
      searchModal_placeholder: 'e.g., "What were the latest AI developments this week?"',
      searchModal_cancel: 'Cancel',
      searchModal_search: 'Search',
      searchModal_searching: 'Searching...',
      whatIf_title: 'Hypothetical Scenario Analysis',
      whatIf_heading: 'Describe a Scenario',
      whatIf_description: "Aura will analyze the potential outcomes of this 'what if' scenario.",
      whatIf_placeholder: 'e.g., "What if I decided to learn a new programming language?"',
      whatIf_cancel: 'Cancel',
      whatIf_analyze: 'Analyze',
      whatIf_analyzing: 'Analyzing...',
      strategicGoal_title: 'Set Strategic Goal',
      strategicGoal_heading: 'Define a High-Level Goal',
      strategicGoal_description: "Aura will decompose this goal into a tree of tactical and operational sub-goals.",
      strategicGoal_placeholder: 'e.g., "Help me build a personal website from scratch."',
      strategicGoal_cancel: 'Cancel',
      strategicGoal_setGoal: 'Set Goal',
      strategicGoal_decomposing: 'Decomposing Goal...',
      forecastModal_title: 'Internal State Forecast',
      forecastModal_description: 'Predicts the decay of core signals over the next minute if Aura remains idle.',
      multiverse_title: 'Branch Noetic Multiverse',
      multiverse_heading: 'Explore an Alternative Path',
      multiverse_description: 'Propose an alternative line of reasoning or a different perspective for Aura to explore in parallel.',
      multiverse_placeholder: 'e.g., "Instead of focusing on efficiency, consider the most creative solution."',
      multiverse_cancel: 'Cancel',
      multiverse_branch: 'Branch',
      multiverse_branching: 'Branching...',
      brainstorm_title: 'Brainstorming Session',
      brainstorm_heading: 'Enter a Topic',
      brainstorm_description: 'Aura will generate a variety of ideas related to this topic.',
      brainstorm_placeholder: 'e.g., "Ideas for a sci-fi story".',
      brainstorm_cancel: 'Cancel',
      brainstorm_generate: 'Generate',
      brainstorm_processing: 'Brainstorming...',
      advancedControlsModal_title: 'Advanced Controls & System Panels',

      // --- And many more... this is a representative sample. All title keys have been updated. ---
    },
  },
  ja: {
    translation: {
      nativeName: '日本語',
      localization_label: '言語',
      chatTab: 'チャット',
      monitorTab: 'モニター',
      // ... other japanese translations would go here
    }
  }
};