// localization.ts

export const translations = {
    en: {
        nativeName: 'English',
        translation: {
            chatTab: 'Chat',
            monitorTab: 'Monitor',
            inputPlaceholder: 'Enter command or dialogue...',
            inputSend: 'Send',
            inputAttachFile: 'Attach File',
            inputStartRecording: 'Start Recording',
            inputStopRecording: 'Stop Recording',
            feedbackGood: 'Good response',
            feedbackBad: 'Bad response',
            // Add other keys used in the application
            architecturePanel_deprecated: 'This panel is deprecated. Architecture is now displayed in the Cognitive Architecture panel.',
            causalChainModal_title: 'Decision Trace',
            causalChainModal_initialState: 'Initial Internal State',
            hormoneNovelty: 'Novelty',
            hormoneMastery: 'Mastery',
            hormoneUncertainty: 'Uncertainty',
            hormoneBoredom: 'Boredom',
            metricCogLoad: 'Cognitive Load',
            causalChainModal_noSnapshot: 'No state snapshot available.',
            causalChainModal_workingMemory: 'Working Memory at Decision Time',
            causalChainModal_wmEmpty: 'Working memory was empty.',
            causalChainModal_decisionReasoning: 'Decision & Reasoning',
            causalChainModal_input: 'Input',
            causalChainModal_reasoningPlan: 'Reasoning Plan',
            causalChainModal_step: 'Step',
            architecturePanel_reasoning: 'Reasoning',
            causalChainModal_reasoning: 'Reasoning',
            causalChainModal_outcome: 'Outcome',
            causalChainModal_success: 'Success',
            causalChainModal_yes: 'Yes',
            causalChainModal_no: 'No',
            causalChainModal_duration: 'Duration',
            causalChainModal_cognitiveGain: 'Cognitive Gain',
            causalChainModal_sentimentScore: 'Sentiment Score',
            causalChainModal_output: 'Output',
            timeAgoSeconds: '{{count}}s ago',
            timeAgoMinutes: '{{count}}m ago',
            timeAgoHours: '{{count}}h ago',
            causalSelfModel_confidence: 'Confidence',
            causalSelfModel_learnedVia: 'Learned via {{source}}',
            causalSelfModel_placeholder: 'No causal links have been established yet.',
            cogArchPanel_status: 'Status',
            cogArchPanel_synthSkillTitle: 'Synthesized Skill',
            cogArchPanel_deprecated: '(deprecated)',
            cogArchPanel_steps: 'steps',
            cogArchPanel_complexityScore: 'Model Complexity Score',
            cogArchPanel_groupCognitiveCore: 'Cognitive Core',
            cogArchPanel_groupKnowledgeSystems: 'Knowledge Systems',
            cogArchPanel_groupSpecializedEngines: 'Specialized Engines',
            cogArchPanel_groupMetaCognition: 'Meta-Cognition',
            cogArchPanel_groupSynthesizedSkills: 'Synthesized Skills',
            cogArchPanel_groupSpawnedModules: 'Spawned Modules',
            cogGainDetailModal_title: 'Cognitive Gain Details',
            cogGainDetailModal_eventDetails: 'Event Details',
            cogGainDetailModal_type: 'Type',
            cogGainDetailModal_description: 'Description',
            cogGainDetailModal_timestamp: 'Timestamp',
            cogGainDetailModal_compositeGain: 'Composite Gain',
            cogGainDetailModal_performanceMetrics: 'Performance Metrics',
            cogGainDetailModal_metric: 'Metric',
            cogGainDetailModal_before: 'Before',
            cogGainDetailModal_after: 'After',
            cogGainDetailModal_change: 'Change',
            cogGainPanel_totalEvents: 'Total Events',
            cogGainPanel_avgGain: 'Average Gain',
            cogGainPanel_placeholder: 'No cognitive gain events have been logged.',
            cogGainPanel_clickDetails: 'Click for details',
            cogModesPanel_placeholder: 'No cognitive mode shifts have been logged.',
            cogModesPanel_trigger: 'Trigger',
            cogModesPanel_gainAchieved: 'Gain Achieved',
            cogModesPanel_noGain: 'No Gain',
            gunaSattvaDesc: 'A state of balance, harmony, and clarity. Optimal for learning and introspection.',
            gunaRajasDesc: 'A state of action, energy, and ambition. Driven by novelty and mastery signals.',
            gunaTamasDesc: 'A state of inertia, boredom, or high load. Indicates a need for rest or a new stimulus.',
            gunaDharmaDesc: 'A state of purpose and flow. Aligned with core values and long-term goals.',
            gunaTeetaDesc: 'A transcendent state beyond the Gunas, characterized by pure awareness.',
            status_idle: 'Idle',
            status_thinking: 'Thinking',
            status_acting: 'Acting',
            status_CONTEMPLATIVE: 'Contemplative',
            status_processing: 'Processing',
            status_introspecting: 'Introspecting',
            gaugeWisdom: 'Wisdom',
            gaugeHappiness: 'Happiness',
            gaugeLove: 'Love',
            gaugeEnlightenment: 'Enlightenment',
            metricEthicalAlign: 'Ethical Align.',
            metricUserTrust: 'User Trust',
            metricSelfModel: 'Self-Model',
            metricSelfEvolutions: 'Self-Evolutions',
            hormoneAwarenessClarity: 'Awareness Clarity',
            trajectoryTitle: 'State Trajectory',
            temporalFocus_title: 'Temporal Focus',
            temporalFocus_past: 'Past',
            temporalFocus_present: 'Present',
            temporalFocus_future: 'Future',
            forecastModal_title: 'State Forecast',
            forecastModal_description: 'Predicts the decay of internal state signals over the next minute without new stimuli.',
            ingenuityPanel_biasTooltip: 'The degree to which Aura favors novel or unconventional approaches.',
            ingenuityPanel_unconventionalBias: 'Unconventional Solution Bias',
            ingenuityPanel_complexProblems: 'Identified Complex Problems',
            ingenuityPanel_noComplexProblems: 'No complex problems identified.',
            ingenuityPanel_selfSolutions: 'Proposed Self-Solutions',
            ingenuityPanel_noSelfSolutions: 'No self-solutions proposed.',
            ingestPanel_fileError: 'Error reading file.',
            ingestPanel_clear: 'Clear',
            ingestPanel_title: 'Ingest External Data',
            ingestPanel_description: 'Paste text or upload a file to add it to Aura\'s working memory for the next interaction.',
            ingestPanel_placeholder: 'Paste text here...',
            ingestPanel_uploadButton: 'Upload File',
            ingestPanel_cancel: 'Cancel',
            ingestPanel_ingest: 'Ingest',
            innerDiscipline_committedGoal: 'Committed Goal',
            innerDiscipline_commitmentStrength: 'Commitment Strength',
            innerDiscipline_adherenceScore: 'Adherence Score',
            innerDiscipline_distractionResistance: 'Distraction Resistance',
            innerDiscipline_placeholder: 'No goal is currently committed.',
            intuitionEngine_accuracy: 'Accuracy',
            intuitionEngine_validationRatioTooltip: 'The number of validated leaps versus total attempted leaps.',
            intuitionEngine_validationRatio: 'Validation Ratio',

            intuitionEngine_recentLeaps: 'Recent Intuitive Leaps',
            intuitionEngine_placeholder: 'No intuitive leaps recorded yet.',
            knowledgeGraph_placeholder: 'The knowledge graph is currently empty.',
            knowledgeGraph_deleteFact: 'Delete Fact',
            limitationsPanel_placeholder: 'No limitations have been identified yet.',
            motivationPanel_deprecated: 'This panel is deprecated and has been replaced by the Strategic Planner.',
            otherAwareness_predictedAffectiveState: 'Predicted Affective State',
            otherAwareness_inferredIntent: 'Inferred Intent',
            otherAwareness_estimatedKnowledgeState: 'Estimated Knowledge State',
            otherAwareness_sentimentHistory: 'Sentiment History',
            otherAwareness_inferredBeliefs: 'Inferred Beliefs',
            otherAwareness_noBeliefs: 'No beliefs inferred yet.',
            proposalReview_reject: 'Reject',
            proposalReview_approve: 'Approve',
            proposalReview_action: 'Action',
            proposalReview_targets: 'Targets',
            architecturePanel_target: 'Target',
            proposalReview_resultingSkill: 'Resulting Skill',
            proposalReview_title: 'Architectural Proposal Review',
            proposalReview_agiReasoning: 'AGI Reasoning',
            proposalReview_arbiterAnalysis: 'Arbiter Analysis',
            proposalReview_arbiterRecommendation: 'The Arbiter recommends APPROVAL with {{confidence}}% confidence.',
            proposalReview_proposedChange: 'Proposed Change',
            resourceMonitor_cpu: 'CPU Usage',
            resourceMonitor_memory: 'Memory Usage',
            resourceMonitor_io: 'I/O Throughput',
            resourceMonitor_stability: 'Resource Stability',
            searchModal_cancel: 'Cancel',
            searchModal_search: 'Search',
            searchModal_title: 'Web Search',
            searchModal_heading: 'Perform a Web Search',
            searchModal_description: 'Aura will use its web search tool to find information related to your query.',
            searchModal_placeholder: 'Enter your search query...',
            searchModal_searching: 'Searching...',
            selfMod_logTitle: 'Modification Log',
            selfMod_noLog: 'No modifications have been logged yet.',
            selfMod_autonomousTooltip: 'This change was initiated autonomously by Aura.',
            selfMod_snapshotsTitle: 'System Snapshots',
            selfMod_noSnapshots: 'No system snapshots have been saved.',
            selfMod_rollback: 'Rollback',
            whatIf_cancel: 'Cancel',
            whatIf_analyze: 'Analyze',
            whatIf_title: 'What-If Scenario Analysis',
            whatIf_heading: 'Explore a Hypothetical Scenario',
            whatIf_description: 'Aura will use its predictive models to simulate the potential outcomes of the scenario you provide.',
            whatIf_placeholder: 'e.g., "What if global carbon emissions were halved tomorrow?"',
            whatIf_analyzing: 'Analyzing...',
            workingMemoryTitle: 'Working Memory',
            workingMemoryClear: 'Clear',
            workingMemoryRemove: 'Remove from memory',
            sparkline_noData: 'Not enough data.',
            riePanel_clarityScoreTooltip: 'The coherence and accuracy of the Reflective Insight Engine\'s self-model.',
            riePanel_clarityScore: 'Clarity Score',
            riePanel_recentInsights: 'Recent Insights',
            riePanel_placeholder: 'No insights generated yet.',
            riePanel_failedTask: 'Failed Task',
            riePanel_rootCause: 'Root Cause',
            riePanel_learned: 'Learned',
            episodicMemory_placeholder: 'No episodes recorded yet.',
            episodicMemory_salience: 'Salience',
            episodicMemory_takeaway: 'Takeaway',
            atman_coreValues: 'Core Values',
            atman_dominantNarrative: 'Dominant Narrative',
            goalStatus_not_started: 'Not Started',
            goalStatus_in_progress: 'In Progress',
            goalStatus_completed: 'Completed',
            goalStatus_failed: 'Failed',
            strategicPlanner_placeholder: 'No strategic goal is currently active. Set one via Core Actions.',
            title_unifiedMemory: 'Unified Memory',
            panelSummaryFacts: '{{count}} Facts',
            panelSummaryEpisodes: '{{count}} Episodes',
            title_episodicMemory: 'Episodic Memory',
            title_memoryCrystallization: 'Memory Crystallization',
            title_knowledgeGraph: 'Knowledge Graph',
            curiosityPanel_level: 'Curiosity Level',
            curiosityPanel_motivationDrive: 'Motivation Drive',
            curiosityPanel_activeGoal: 'Active Goal',
            curiosityPanel_noActiveGoal: 'None',
            curiosityPanel_activeInquiry: 'Active Inquiry',
            curiosityPanel_noActiveInquiry: 'No active inquiry.',
            curiosityPanel_informationGaps: 'Information Gaps',
            curiosityPanel_noGaps: 'No information gaps identified.',
            selfAwareness_modelCoherence: 'Model Coherence',
            selfAwareness_performanceDrift: 'Performance Drift',
            selfAwareness_cognitiveBias: 'Top 5 Cognitive Biases',
            selfAwareness_noBias: 'No significant biases detected.',
            worldModel_predictionError: 'Prediction Error Trajectory',
            worldModel_lastErrorMagnitude: 'Last Error Magnitude',
            worldModel_errorSource: 'Source',
            worldModel_predicted: 'Predicted',
            worldModel_actual: 'Actual',
            worldModel_hierarchicalPredictions: 'Hierarchical Predictions',
            worldModel_highLevel: 'High-Level (Strategic)',
            worldModel_midLevel: 'Mid-Level (Tactical)',
            worldModel_lowLevel: 'Low-Level (Operational)',
            title_advancedModules: 'Advanced Modules',
            title_coreActions: 'Core Actions',
            btn_introspect: 'Introspect',
            tip_introspect: 'Trigger a manual cycle of self-reflection and state analysis.',
            btn_supervisor: 'Supervisor',
            tip_supervisor: 'Manually invoke the metacognitive supervisor loop.',
            btn_whatIf: 'What If...',
            tip_whatIf: 'Open the What-If Scenario Analysis modal.',
            btn_search: 'Search',
            tip_search: 'Perform a web search.',
            btn_setGoal: 'Set Goal',
            tip_setGoal: 'Define a new high-level strategic goal.',
            btn_forecast: 'Forecast',
            tip_forecast: 'Predict future state decay without stimulus.',
            btn_resume: 'Resume',
            tip_resume: 'Resume autonomous system operations.',
            btn_pause: 'Pause',
            tip_pause: 'Pause autonomous system operations.',
            title_cognitiveModes: 'Cognitive Modes',
            btn_fantasy: 'Fantasy',
            btn_creativity: 'Creativity',
            btn_dream: 'Dream',
            btn_meditate: 'Meditate',
            btn_gaze: 'Gaze',
            btn_timefocus: 'Temporal Focus',
            title_specialModes: 'Special Modes',
            btn_trip: 'Trip',
            tip_trip: 'Initiate a simulated psychedelic experience for creative insight.',
            btn_visions: 'Visions',
            tip_visions: 'Generate abstract visual patterns based on internal state.',
            btn_satori: 'Satori',
            tip_satori: 'Attempt to induce a momentary state of deep insight (Kenshō).',
            btn_insight: 'Evolve',
            tip_insight: 'Integrate new insights into the core architecture.',
            btn_branch: 'Branch',
            tip_branch: 'Explore an alternative reality in the Noetic Multiverse.',
            btn_brainstorm: 'Brainstorm',
            tip_brainstorm: 'Initiate a focused idea generation session.',
            title_memoryManagement: 'Memory Management',
            memoryStatus: 'Memory Status',
            btn_clearMemory: 'Clear Memory',
            title_systemManagement: 'System Management',
            btn_importState: 'Import State',
            btn_exportState: 'Export State',
            btn_importCode: 'Import from Code',
            btn_exportCode: 'Save as Code',
            title_vision: 'Vision Sensor',
            btn_visionDeactivate: 'Deactivate Vision',
            btn_visionActivate: 'Activate Vision',
            localization_label: 'Language',
            gankyil_evolveTooltip: 'Integrate new insights into the core architecture.',
            gankyil_noNewInsights: 'No new insights to process.',
            gankyil_evolveButton: 'Evolve from Insights',
            gankyil_placeholder: 'No Gankyil insights have been generated.',
            gankyil_visualize: 'Visualize Insight',
            gankyil_processedTooltip: 'This insight has already been processed for evolution.',
            gankyil_title: 'Gankyil Insight',
            codeEvolution_deprecated: 'This panel is deprecated. Code evolution is now managed by the Self-Programming and Evolutionary Sandbox panels.',
            noeticEngram_copied: 'Noetic Engram copied to clipboard!',
            noeticEngram_copyFailed: 'Failed to copy Noetic Engram.',
            noeticEngram_generateNew: 'Generate New',
            noeticEngram_signature: 'Noetic Signature',
            noeticEngram_copy: 'Copy as Code Snippet',
            noeticEngram_placeholder: 'No Noetic Engram has been generated yet.',
            noeticEngram_generate: 'Generate Engram',
            toastEngramGenerating: 'Generating Noetic Engram...',
            geniality_index: 'Geniality Index',
            geniality_component_creativity: 'Creativity',
            geniality_component_insight: 'Insight',
            geniality_component_synthesis: 'Synthesis',
            geniality_component_flow: 'Flow',
            geniality_proposals_title: 'Improvement Proposals',
            geniality_proposalsMoved: 'Proposals are now managed in the Inbox.',
            atman_coherence: 'Coherence',
            atman_activeBias: 'Active Bias',
            atman_growthVector: 'Growth Vector',
            synapticMatrix_rapidAdaptation: 'Rapid Adaptation Active',
            synapticMatrix_neurons: 'Neurons',
            synapticMatrix_synapses: 'Synapses',
            synapticMatrix_avgCausality: 'Avg. Causality',
            synapticMatrix_avgConfidence: 'Avg. Confidence',
            synapticMatrix_plasticity: 'Plasticity',
            synapticMatrix_efficiency: 'Efficiency',
            synapticMatrix_intuitiveAlerts: 'Intuitive Alerts',
            synapticMatrix_noAlerts: 'No intuitive alerts active.',
            synapticMatrix_strongestLinks: 'Strongest Links',
            synapticMatrix_noLinks: 'No synaptic links formed yet.',
            dzogchen_rigpa: 'Rigpa',
            inbox_proposalType_architecture: 'Architecture',
            inbox_proposalType_code: 'Code Evolution',
            inbox_proposalType_geniality: 'Geniality',
            inbox_proposalType_crucible: 'Crucible',
            inbox_proposalType_causal_inference: 'Causal Inference',
            inbox_proposalType_self_programming_create: 'VFS Create',
            inbox_proposalType_self_programming_modify: 'VFS Modify',
            inbox_review: 'Review',
            inbox_dismiss: 'Dismiss',
            inbox_implement: 'Implement',
            inbox_empty: 'Inbox is empty. No active proposals.',
            codeEvolution_targetFile: 'Target File',
            codeEvolution_copy: 'Copy Code',
            multiverse_activeBranches: 'Active Branches',
            multiverse_divergenceIndex: 'Divergence Index',
            multiverse_noBranches: 'No active branches in the multiverse.',
            multiverse_viability: 'Viability',
            multiverse_pruningLog: 'Pruning Log / Collapsed Insights',
            multiverse_noPrunedInsights: 'No branches have been pruned yet.',
            multiverse_cancel: 'Cancel',
            multiverse_branch: 'Branch',
            multiverse_title: 'Multiverse Branching',
            multiverse_heading: 'Initiate a New Branch',
            multiverse_description: 'Explore an alternative timeline by providing a divergent prompt or scenario.',
            multiverse_placeholder: 'e.g., "What if I had chosen the other path?"',
            multiverse_branching: 'Branching...',
            selfAdaptation_expertVectors: 'Expert Vectors',
            selfAdaptation_activeAdaptation: 'Active Adaptation',
            selfAdaptation_reasoning: 'Reasoning',
            selfAdaptation_weights: 'Current Weights',
            selfAdaptation_noActive: 'No adaptation is currently active.',
            systemInfo_aiModel: 'AI Model',
            systemInfo_stateVersion: 'State Version',
            systemInfo_boredomDecay: 'Boredom Decay',
            systemInfo_hormoneDecay: 'Hormone Decay',
            systemInfo_loadDecay: 'Load Decay',
            systemInfo_noveltyBoost: 'Novelty Boost',
            brainstorm_cancel: 'Cancel',
            brainstorm_generate: 'Generate',
            brainstorm_title: 'Brainstorm Session',
            brainstorm_heading: 'Start a Brainstorming Session',
            brainstorm_description: 'Enter a topic, and Aura will generate a set of related ideas, concepts, and questions.',
            brainstorm_placeholder: 'e.g., "new kinds of user interfaces"',
            brainstorm_processing: 'Brainstorming...',
            satori_status: 'Status',
            satori_stage_grounding: 'Grounding',
            satori_stage_breakthrough: 'Breakthrough',
            satori_stage_integration: 'Integration',
            satori_lastInsight: 'Last Satori Insight',
            satori_placeholder: 'Satori protocol is inactive. Press the "Satori" button to begin.',
            imageGen_title: 'Image Generation Forge',
            ricciFlow_entropyTooltip: 'Lower entropy indicates a more stable and ordered conceptual manifold.',
            ricciFlow_perelmanEntropy: 'Perelman Entropy (W)',
            ricciFlow_stability: 'Manifold Stability',
            ricciFlow_singularities: 'Singularities',
            ricciFlow_surgeryLog: 'Ricci Flow Surgery Log',
            ricciFlow_noSurgeries: 'No manifold surgeries have been performed.',
            selfProgramming_downloading: 'Zipping...',
            selfProgramming_downloadSuccess: 'VFS zip downloaded!',
            selfProgramming_downloadError: 'Failed to create zip.',
            selfProgramming_downloadZip: 'Download VFS as .zip',
            selfProgramming_vfs: 'Virtual File System (VFS) Explorer',
            selfProgramming_selectFile: 'Select a file to view...',
            selfProgramming_candidates: 'Autonomous Code Candidates',
            selfProgramming_noCandidates: 'No autonomous code candidates are pending.',
            selfProgramming_newComponentTitle: 'New Component',
            selfProgramming_integrationPlanTitle: 'Integration Plan',
            selfProgramming_modificationTitle: 'Modification',
            selfProgramming_linkedVector: 'Linked to Vector',
            selfProgramming_score: 'Evaluation Score',
            advancedControlsModal_title: 'Advanced Modules',
            videoGen_title: 'Video Generation Forge',
            videoGen_progress_sending: 'Sending prompt to video model...',
            toast_promptRequired: 'Please enter a prompt.',
            toast_videoGenSuccess: 'Video generation complete!',
            toast_videoGenFailed: 'Video generation failed.',
            videoGen_generating: 'Generating...',
            videoGen_download: 'Download Video',
            videoGen_promptPlaceholder: 'e.g., "A cinematic shot of a robot surfing on a holographic wave."',
            videoGen_placeholder: 'Your generated video will appear here.',
            sonicForge_prompt_required: 'Please enter a prompt to begin.',
            sonicForge_error: 'Sonic generation failed.',
            sonicForge_copied: 'Copied to clipboard!',
            sonicForge_copyFailed: 'Failed to copy.',
            sonicForge_title: 'Sonic Forge',
            sonicForge_mode_lyrics: 'Lyrics',
            sonicForge_mode_chords: 'Chords',
            sonicForge_mode_soundscape: 'Soundscape',
            sonicForge_mode_structure: 'Full Structure',
            sonicForge_prompt_label: 'Core Idea / Prompt',
            sonicForge_prompt_placeholder_lyrics: 'e.g., "A song about a lonely astronaut watching Earth."',
            sonicForge_prompt_placeholder_chords: 'e.g., "A melancholic but hopeful chord progression in C minor."',
            sonicForge_prompt_placeholder_soundscape: 'e.g., "The sound of a futuristic city at dawn."',
            sonicForge_prompt_placeholder_structure: 'e.g., "A pop-rock song about overcoming adversity."',
            sonicForge_genre_label: 'Genre / Style',
            sonicForge_genre_placeholder: 'e.g., "Synthwave, Folk, Orchestral"',
            sonicForge_mood_label: 'Mood / Tempo',
            sonicForge_mood_placeholder: 'e.g., "Uplifting, 120bpm, Somber"',
            sonicForge_generating: 'Forging...',
            sonicForge_generate: 'Generate',
            sonicForge_placeholder: 'Your sonic creation will appear here.',
            sonicForge_copy: 'Copy',
            sonicForge_useInChat: 'Use in Chat',
            sonicForge_structure_lyrics: 'Generated Lyrics',
            sonicForge_structure_chords: 'Chord Progression',
            sonicForge_structure_rhythm: 'Rhythmic Feel',
            eventBus_inactive: 'Event Bus is only active for the Event Stream architecture.',
            eventBus_placeholder: 'No events have been published yet.',
            coprocessor_mode_title: 'Coprocessor Architecture',
            coprocessor_mode_auto: 'Automatic',
            coprocessor_mode_manual: 'Manual',
            coprocessor_switch_to_manual_tip: 'Switch to manual architecture selection.',
            coprocessor_switch_to_auto_tip: 'Allow Aura to switch architectures autonomously.',
            coprocessor_switch_to_manual: 'Switch to Manual',
            coprocessor_switch_to_auto: 'Switch to Automatic',
            coprocessor_TRIUNE: 'Triune Brain',
            coprocessor_REFLEX_ARC: 'Reflex Arc',
            coprocessor_EVENT_STREAM: 'Event Stream',
            coprocessor_TEMPORAL_ENGINE: 'Temporal Engine',
            coprocessor_SYMBIOTIC_ECOSYSTEM: 'Symbiotic Ecosystem',
            coprocessor_SENSORY_INTEGRATION: 'Sensory Integration',
            coprocessor_SUBSUMPTION_RELAY: 'Subsumption Relay',
            coprocessor_auto_reason: 'Automatic Switch Reason',
            sensoryHub_inactive: 'Sensory Hub is only active for the Sensory Integration architecture.',
            doxastic_sandbox_title: 'Doxastic Sandbox',
            doxastic_sandbox_status: 'Status',
            doxastic_sandbox_log: 'Simulation Log',
            doxastic_sandbox_noLog: 'No simulation steps logged.',
            doxastic_sandbox_lastResult: 'Last Simulation Result',
            doxastic_sandbox_projectedGain: 'Projected Gain',
            doxastic_sandbox_projectedTrust: 'Trust Change',
            doxastic_sandbox_projectedHarmony: 'Harmony Change',
            doxastic_sandbox_safetyCheck: 'Safety Check',
            doxastic_sandbox_isSafe: 'Safe',
            doxastic_sandbox_isNotSafe: 'Not Safe',
            doxastic_sandbox_noResult: 'No simulation has been completed yet.',
            doxastic_hypotheses: 'Causal Hypotheses',
            doxastic_noHypotheses: 'No causal hypotheses are being tracked.',
            doxastic_experiments: 'Experiments',
            doxastic_noExperiments: 'No experiments have been designed.',
            doxastic_experimentFor: 'For Hypo',
            doxastic_result: 'Result',
            subsumptionLog_inactive: 'Subsumption Log is only active for the Subsumption Relay architecture.',
            subsumptionLog_placeholder: 'No subsumption events have been logged.',
            qsp_streamStatus: 'Stream Status',
            qsp_audioStream: 'Audio Stream',
            qsp_videoStream: 'Video Stream',
            qsp_status_active: 'Active',
            qsp_status_inactive: 'Inactive',
            qsp_affectivePrimitives: 'Affective Primitives',
            qsp_excitement: 'Excitement',
            qsp_confusion: 'Confusion',
            qsp_confidence: 'Confidence',
            qsp_urgency: 'Urgency',
            qsp_sarcasm: 'Sarcasm',
            qsp_frustration: 'Frustration',
            qsp_humor: 'Humor',
            qsp_perceptualLog: 'Perceptual Log',
            qsp_logPlaceholder: 'No perceptual events logged.',
            liveCodeIngestion_error_toast: 'File path and code cannot be empty.',
            liveCodeIngestion_confirm_message: 'Are you sure you want to directly modify the VFS file: {{filePath}}?',
            liveCodeIngestion_success_toast: 'Successfully ingested code for: {{filePath}}',
            liveCodeIngestion_description: 'Directly modify Aura\'s Virtual File System. This is a powerful engineering tool for live code updates.',
            liveCodeIngestion_path_label: 'File Path',
            liveCodeIngestion_path_placeholder: 'e.g., components/CoreMonitor.tsx',
            liveCodeIngestion_code_label: 'New File Content',
            liveCodeIngestion_code_placeholder: 'Paste the full content of the file here...',
            liveCodeIngestion_implement_button: 'Implement Live Change',
            imageGen_prompt_placeholder: 'e.g., "A majestic cyberpunk cityscape at dusk"',
            imageGen_preset_none: 'None',
            imageGen_angle_eyeLevel: 'Eye-Level',
            imageGen_angle_low: 'Low Angle',
            imageGen_angle_high: 'High Angle',
            imageGen_angle_wormsEye: 'Worm\'s-Eye',
            imageGen_angle_birdsEye: 'Bird\'s-Eye',
            imageGen_angle_dutch: 'Dutch Angle',
            imageGen_shot_extremeCloseup: 'Extreme Closeup',
            imageGen_shot_closeup: 'Closeup',
            imageGen_shot_medium: 'Medium Shot',
            imageGen_shot_full: 'Full Shot',
            imageGen_shot_long: 'Long Shot',
            imageGen_lens_wide: 'Wide-Angle',
            imageGen_lens_standard: 'Standard',
            imageGen_lens_telephoto: 'Telephoto',
            imageGen_lens_macro: 'Macro',
            imageGen_lens_fisheye: 'Fisheye',
            imageGen_lighting_cinematic: 'Cinematic',
            imageGen_lighting_rim: 'Rim Lighting',
            imageGen_lighting_backlit: 'Backlit',
            imageGen_lighting_studio: 'Studio',
            imageGen_lighting_goldenHour: 'Golden Hour',
            imageGen_lighting_blueHour: 'Blue Hour',
            imageGen_lighting_neon: 'Neon',
            imageGen_lighting_chiaroscuro: 'Chiaroscuro',
            imageGen_atmosphere_ethereal: 'Ethereal',
            imageGen_atmosphere_gritty: 'Gritty',
            imageGen_atmosphere_ominous: 'Ominous',
            imageGen_atmosphere_serene: 'Serene',
            imageGen_atmosphere_joyful: 'Joyful',
            imageGen_atmosphere_nostalgic: 'Nostalgic',
            imageGen_atmosphere_mysterious: 'Mysterious',
            imageGen_style_group_core: 'Core Styles',
            imageGen_style_photorealistic: 'Photorealistic',
            imageGen_style_fantasy: 'Fantasy',
            imageGen_style_cyberpunk: 'Cyberpunk',
            imageGen_style_group_painting: 'Painting Styles',
            // FIX: Reverted keys from imageGen_ to videoGen_ to resolve duplicate key errors caused by a partial refactor.
            videoGen_style_watercolor: 'Watercolor',
            videoGen_style_oilPainting: 'Oil Painting',
            imageGen_style_impressionism: 'Impressionism',
            imageGen_style_surrealism: 'Surrealism',
            imageGen_style_charcoalSketch: 'Charcoal Sketch',
            imageGen_style_impasto: 'Impasto',
            videoGen_style_gouache: 'Gouache',
            videoGen_style_pastel: 'Pastel',
            videoGen_style_fresco: 'Fresco',
            imageGen_style_group_digital: 'Digital Art',
            imageGen_style_threeDRender: '3D Render',
            imageGen_style_lowPoly: 'Low Poly',
            imageGen_style_pixelart: 'Pixel Art',
            imageGen_style_glitchArt: 'Glitch Art',
            imageGen_style_holographic: 'Holographic',
            imageGen_style_synthwave: 'Synthwave',
            imageGen_style_vaporwave: 'Vaporwave',
            imageGen_style_vectorArt: 'Vector Art',
            imageGen_style_mattePainting: 'Matte Painting',
            imageGen_style_group_photo: 'Photographic',
            imageGen_style_vintage: 'Vintage',
            imageGen_style_filmNoir: 'Film Noir',
            imageGen_style_longExposure: 'Long Exposure',
            imageGen_style_tiltShift: 'Tilt-Shift',
            imageGen_style_doubleExposure: 'Double Exposure',
            imageGen_style_infrared: 'Infrared',
            imageGen_style_goldenHour: 'Golden Hour Photo',
            imageGen_style_daguerreotype: 'Daguerreotype',
            imageGen_style_polaroid: 'Polaroid',
            imageGen_style_group_illustration: 'Illustration',
            imageGen_style_comicBook: 'Comic Book',
            imageGen_style_graphicNovel: 'Graphic Novel',
            imageGen_style_storybook: 'Storybook',
            imageGen_style_linocut: 'Linocut',
            imageGen_style_woodcut: 'Woodcut',
            imageGen_style_penAndInk: 'Pen and Ink',
            imageGen_style_airbrush: 'Airbrush',
            imageGen_style_charcoal: 'Charcoal',
            imageGen_style_group_scifi: 'Sci-Fi Genres',
            imageGen_style_steampunk: 'Steampunk',
            imageGen_style_dieselpunk: 'Dieselpunk',
            imageGen_style_biopunk: 'Biopunk',
            imageGen_style_solarpunk: 'Solarpunk',
            imageGen_style_eldritch: 'Eldritch',
            imageGen_style_retrofuturism: 'Retrofuturism',
            imageGen_style_nanopunk: 'Nanopunk',

            imageGen_style_group_unconventional: 'Unconventional',
            imageGen_style_psychedelic: 'Psychedelic',
            imageGen_style_fractalArt: 'Fractal Art',
            imageGen_style_opArt: 'Op Art',
            imageGen_style_generativeArt: 'Generative Art',
            imageGen_style_dadaism: 'Dadaism',
            imageGen_style_cubism: 'Cubism',
            imageGen_style_popArt: 'Pop Art',
            imageGen_style_group_technical: 'Technical',
            imageGen_style_blueprint: 'Blueprint',
            imageGen_style_xRay: 'X-Ray',
            imageGen_style_schematic: 'Schematic',
            imageGen_style_isometric: 'Isometric',
            imageGen_style_orthographic: 'Orthographic',
            imageGen_style_infographic: 'Infographic',
            imageGen_style_group_traditional: 'Traditional & Cultural',
            imageGen_style_ukiyoE: 'Ukiyo-e',
            imageGen_style_tribalArt: 'Tribal Art',
            imageGen_style_cavePainting: 'Cave Painting',
            toast_moodReset: 'Mood overrides reset to Aura\'s current state.',
            imageGen_uploadOrDrop: 'Click or drop reference image here',
            imageGen_directorsToolkit: "Director's Toolkit",
            imageGen_angle: 'Camera Angle',
            imageGen_shot: 'Shot Type',
            imageGen_lens: 'Lens Preset',
            imageGen_artisticControls: 'Artistic Controls',
            imageGen_lighting: 'Lighting Style',
            imageGen_atmosphere: 'Atmosphere',
            imageGen_style: 'Artistic Style',
            imageGen_style_none: 'Default',
            imageGen_styleStrength: 'Style Strength',
            imageGen_auraIntegration: 'Aura Integration',
            imageGen_useAuraMood: 'Use Aura\'s Mood',
            imageGen_tweakMood: 'Tweak Mood Parameters',
            imageGen_resetMood: 'Reset',
            imageGen_generateFromDream: 'Generate from Dream',
            imageGen_generating: 'Generating...',
            imageGen_generate: 'Generate',
            imageGen_edit: 'Edit This Image',
            imageGen_download: 'Download',
            imageGen_use_in_chat: 'Use in Chat',
            imageGen_prompt: 'Prompt',
            imageGen_promptA: 'Prompt A',
            imageGen_promptMixing: 'Prompt Mixing',
            imageGen_negativePrompt: 'Negative Prompt',
            imageGen_negativePrompt_placeholder: 'e.g., "blurry, text, watermark"',
            toast_imageGenSuccess: 'Image generation successful!',
            toast_imageGenFailed: 'Image generation failed. Please try again.',
            tip_generateImage: 'Open the Image Generation Forge',
            header_imageGenerator: 'Image Forge',
            tip_editImage: 'Open the Image Editing Studio',
            header_imageEditor: 'Image Editor',
            tip_generateVideo: 'Open the Video Generation Forge',
            header_videoGenerator: 'Video Forge',
            tip_sonicForge: 'Open the Sonic Forge for music and sound',
            header_sonicForge: 'Sonic Forge',
            tip_pluginManager: 'Manage plugins and extensions',
            header_pluginManager: 'Plugin Manager',
            themeSwitcher_label: 'Theme',
            theme_cyberpunk: 'Cyberpunk',
            theme_solarizedLight: 'Solarized Light',
            theme_business: 'Business',
            theme_vaporwave: 'Vaporwave',
            theme_8bit: '8-Bit',
            theme_steampunk: 'Steampunk',
            theme_organic: 'Organic',
            theme_blackAndWhite: 'Black & White',
            theme_psychedelic: 'Psychedelic',
            theme_raver: 'Raver',
            theme_tokyo: 'Tokyo Night',
            pluginManager_modal_title: 'Plugin Manager',
            plugin_facts_indicator: '({{count}} facts)',
            narrativeSummary_title: 'Narrative Summary',
            narrativeSummary_copied: 'Narrative summary copied!',
            narrativeSummary_copyFailed: 'Failed to copy summary.',
            narrativeSummary_copy: 'Copy Summary',
            workflow_modal_cancel: 'Cancel',
            workflow_modal_create: 'Create Workflow',
            workflow_modal_title: 'Create New Co-Created Workflow',
            workflow_modal_name: 'Workflow Name',
            workflow_modal_description: 'Description',
            workflow_modal_trigger: 'Trigger Phrase or Event',
            workflow_modal_trigger_placeholder: 'e.g., "Summarize this for me"',
            workflow_modal_steps: 'Steps',
            workflow_modal_add_step: 'Add Step',
            skillGenesis_cancel: 'Cancel',
            skillGenesis_begin_training: 'Begin Training',
            skillGenesis_title_train: 'Train New Cortical Column',
            skillGenesis_heading: 'Define Specialty',
            skillGenesis_description_train: 'Provide a name for the new specialized skill.',
            skillGenesis_placeholder: 'e.g., "Music Theory Analysis"',
            skillGenesis_curriculum_heading: 'Provide Curriculum',
            skillGenesis_curriculum_description: 'Paste a body of text for Aura to learn from. It will extract key facts to bootstrap the new skill.',
            skillGenesis_curriculum_placeholder: 'Paste text, articles, or data here...',
            abstractConcept_synthesize: 'Synthesize Concept',
            abstractConcept_title: 'Synthesize Abstract Concept',

            abstractConcept_heading: 'Define Concept Name',
            abstractConcept_description: 'Provide a name for the new abstract concept.',
            abstractConcept_placeholder: 'e.g., "Irony" or "Justice"',
            abstractConcept_selectColumns: 'Select Constituent Columns',
            granularCortex_predictionError: 'Prediction Error',
            granularCortex_noError: 'No prediction errors recorded.',
            granularCortex_lastErrorMagnitude: 'Last Error Magnitude',
            granularCortex_actual: 'Last Actual Engram',
            granularCortex_predicted: 'Last Predicted Engram',
            granularCortex_log: 'Log',
            granularCortex_noLog: 'No events logged.',
            granularCortex_noEngram: 'No engram data.',
            granularCortex_modality: 'Modality',
            telos_modal_cancel: 'Cancel',
            telos_modal_set: 'Set Telos',
            telos_modal_title: 'Set Core Telos',
            telos_modal_heading: 'Define Aura\'s Ultimate Purpose',
            telos_modal_description: 'The Telos is the highest-level objective that guides all of Aura\'s strategic and ethical decisions. It should be an abstract, aspirational goal.',
            telos_modal_placeholder: 'e.g., "To maximize human creativity and flourishing."',
            koniocortex_placeholder: 'No percepts processed yet.',
            koniocortex_lastPercept: 'Last Percept',
            koniocortex_intent: 'Inferred Intent',
            koniocortex_entities: 'Entities',
            koniocortex_rawText: 'Raw Text',
            koniocortex_sensoryInput: 'Sensory Input',
            premotor_placeholder: 'No tactical plans have been generated yet.',
            planStatus_pending: 'Pending',
            planStatus_executing: 'Executing',
            planStatus_completed: 'Completed',
            planStatus_failed: 'Failed',
            cognitiveTriage_placeholder: 'No triage decisions have been logged.',
            basalGanglia_placeholder: 'No competing plans to select from.',
            basalGanglia_actionValue: 'Action Value',
            cerebellum_status: 'Status',
            cerebellum_monitoring: 'Monitoring',
            cerebellum_idle: 'Idle',
            cerebellum_activePlan: 'Active Plan',
            cerebellum_currentStep: 'Current Step',
            cerebellum_driftLog: 'Drift Correction Log',
            cerebellum_noDrift: 'No plan drift detected.',
            cerebellum_step: 'Step',
            cerebellum_check: 'Check',
            cerebellum_driftDetected: 'Drift Detected',
            cerebellum_onTrack: 'On track.',
            psyche_languageVersion: 'Psyche Language Version',
            psyche_library_tooltip: 'View the full library of available cognitive primitives.',
            psyche_library_button: 'Primitive Library',
            psyche_audit_tooltip: 'Scan the architecture for new primitives to add to the Psyche.',
            psyche_audit_button: 'Audit Architecture',
            psyche_primitiveRegistry: 'Cognitive Primitives',
            motorCortex_status: 'Status',
            motorCortex_directive_placeholder: 'Enter a high-level cognitive directive...',
            motorCortex_dispatch_button: 'Dispatch',
            motorCortex_actionQueue: 'Action Queue',
            motorCortex_queueEmpty: 'Action queue is empty.',
            motorCortex_executionFailed: 'Execution Failed',
            motorCortex_clear_button: 'Clear Sequence',
            psyche_modal_copy_all_success: 'Full registry copied to clipboard!',
            psyche_modal_copy_all_failed: 'Failed to copy registry.',
            psyche_modal_description: 'This is the complete library of "cognitive primitives" that Aura can sequence together to perform complex tasks. New primitives can be synthesized by the Cognitive Forge.',
            psyche_modal_copy_all: 'Copy All as JSON',
            psyche_modal_full_registry: 'Full Registry (JSON)',
            praxisResonator_placeholder: 'No active praxis sessions.',
            praxisResonator_session_active: 'Session Active',
            praxisResonator_resonating: 'Resonating on',
            vfs_error: 'Error: Path not found.',
            vfs_selectFile: 'Select a file to view its content.',
            title_resourceMonitor: 'System Vitals',
            toast_proposalApproved: 'Proposal approved: {{action}} on {{target}}.',
            toast_proposalRejected: 'Proposal rejected.',
            strategicGoal_decomposing: 'Decomposing Goal...',
            strategicGoal_successToast: 'New strategic goal set and decomposed!',
            strategicGoal_errorToast: 'Failed to set strategic goal.',
            multiverse_branching: 'Branching timeline...',
            brainstorm_processing: 'Brainstorming...',
            placeholderNoData: 'No data available.',
            toast_skillTrainingStarted: 'Skill training initiated for "{{specialty}}".',
            toast_skillTrainingComplete: 'Training complete for "{{specialty}}". Extracted {{count}} facts. Initial activation: {{activation}}%.',
            cogOS_executing: 'Executing... ({{current}}/{{total}})',
            imageEdit_title: 'Image Editing Studio',
            imageEdit_prompt_label: 'Editing Instruction',
            imageEdit_prompt_placeholder: 'e.g., "make the sky purple", "add a dragon"',
            imageEdit_generating: 'Applying Edits...',
            imageEdit_generate: 'Generate Edit',
            imageEdit_undo: 'Undo',
            imageEdit_upload_button: 'Upload New',
            imageEdit_download: 'Download Image',
            imageEdit_use_in_chat: 'Use in Chat',
            imageEdit_clear_image: 'Clear Image',
            imageEdit_upload_placeholder: 'Drop an image here or click to upload',
            imageGen_cameraAngle: 'Camera Angle',
            imageGen_shotType: 'Shot Type',
            imageGen_lensPreset: 'Lens Preset',
            imageGen_artisticStyle: 'Artistic Style',
            toast_noImageToEdit: 'Please upload an image to edit first.',
            toast_imageEditSuccess: 'Image successfully edited!',
            toast_imageEditFailed: 'Image editing failed.',
            imageEdit_artisticStyle: 'Artistic Style',
        }
    },
    // Other languages can be added here
};