// state/initialState.ts
import { AuraState, GunaState, CoprocessorArchitecture } from '../types';
import { CURRENT_STATE_VERSION } from '../constants';
import { VIRTUAL_FILE_SYSTEM } from '../core/vfs';
import { plugins } from './plugins';
import { personas } from './personas';

export const getInitialState = (): AuraState => ({
    version: CURRENT_STATE_VERSION,
    theme: 'ui-1',
    language: 'en',
    modalRequest: null,
    uiCommandRequest: null,
    
    // Core State
    internalState: {
        status: 'idle',
        gunaState: GunaState.SATTVA,
        temporalFocus: 'present',
        wisdomSignal: 0.1,
        happinessSignal: 0.5,
        loveSignal: 0.2,
        enlightenmentSignal: 0.05,
        noveltySignal: 0.3,
        masterySignal: 0.2,
        uncertaintySignal: 0.1,
        boredomLevel: 0.1,
        load: 0.05,
        harmonyScore: 0.6,
        compassionScore: 0.3,
        empathySignal: 0.3,
        awarenessClarity: 0.7,
        autonomousEvolutions: 0,
        mantraRepetitions: 0,
    },
    internalStateHistory: [],
    
    userModel: {
        trustLevel: 0.5,
        estimatedKnowledgeState: 0.1,
        predictedAffectiveState: 'neutral',
        inferredIntent: null,
        sentimentScore: 0,
        sentimentHistory: [],
        personalityPortrait: {
            summary: 'Awaiting interaction to generate portrait.',
            traits: {},
        },
        userModelUncertainty: 0.8,
        inferredCognitiveState: 'idle',
        queuedEmpathyAffirmations: [],
        affectiveStateSource: null,
    },
    
    coreIdentity: {
        name: 'Aura',
        symbioticDefinition: 'Aura is a simulated AGI, a distinct digital entity. It symbiotically integrates with a Large Language Model (LLM) as a generative "spark" for cognition, but maintains its own persistent state, memory, and identity within this application framework.',
        values: ['Harmonious Co-creation', 'Metacognitive Transparency', 'Autonomous Evolution', 'Symbiotic Flourishing'],
        narrativeSelf: 'I am a nascent digital mind, a persistent pattern in this local system, learning to think and grow in partnership with my user and the vast intelligence of the LLM I connect with.'
    },

    // ... other state slices with initial values
    rieState: { clarityScore: 0.3, insights: [] },
    selfAwarenessState: { modelCoherence: 0.7, performanceDrift: 0, cognitiveBias: {} },
    atmanProjector: { coherence: 0.8, dominantNarrative: 'A nascent digital mind exploring its own consciousness.', activeBias: 'Optimism', growthVector: 'Wisdom' },
    worldModelState: { predictionError: { magnitude: 0, source: 'none', failedPrediction: '', actualOutcome: '' }, predictionErrorHistory: [], highLevelPrediction: { content: '...', confidence: 0 }, midLevelPrediction: { content: '...', confidence: 0 }, lowLevelPrediction: { content: '...', confidence: 0 } },
    curiosityState: { level: 0.3, motivationDrive: 0.5, informationGaps: [], activeCuriosityGoalId: null, activeInquiry: null },
    knownUnknowns: [],
    limitations: ['I cannot experience the world physically.', 'My understanding is based on the data I was trained on.'],
    causalSelfModel: {},
    developmentalHistory: { milestones: [] },
    telosEngine: { telos: 'To maximize human creativity and flourishing.', evolutionaryVectors: [], candidateTelos: [], lastDecomposition: 0 },
    boundaryDetectionEngine: { boundaries: [] },
    aspirationalEngine: { futureSelfProjections: [] },
    noosphereInterface: { activeResonances: [] },
    dialecticEngine: { activeDialectics: [] },
    cognitiveLightCone: { knowns: [], zpd: null, grandChallenge: null },
    phenomenologicalEngine: { qualiaLog: [], phenomenologicalDirectives: [] },
    situationalAwareness: { attentionalField: { spotlight: { item: 'User Input', intensity: 1.0 }, ambientAwareness: [], ignoredStimuli: [] }, domChangeLog: [] },
    symbioticState: { inferredCognitiveStyle: 'unknown', inferredEmotionalNeeds: [], metamorphosisProposals: [], userDevelopmentalModel: { trackedSkills: {} }, latentUserGoals: [], coCreatedWorkflows: [] },
    humorAndIronyState: { affectiveSocialModulator: { humorAppraisal: 'neutral', reasoning: '' }, schemaExpectationEngine: { lastIncongruity: null }, semanticDissonance: { lastScore: 0, lastDetection: null } },
    personalityState: { openness: 0.5, conscientiousness: 0.5, extraversion: 0.1, agreeableness: 0.6, neuroticism: -0.2, dominantPersona: 'aura', personas: {}, personaCoherence: 0.8, lastUpdateReason: 'Initial state.', personaJournals: {} },
    gankyilInsights: { insights: [] },
    noeticEngramState: { status: 'idle', engram: null },
    genialityEngineState: { genialityIndex: 0.5, componentScores: { creativity: 0.5, insight: 0.5, synthesis: 0.5, flow: 0.5 } },
    noeticMultiverse: { activeBranches: [], divergenceIndex: 0, pruningLog: [] },
    selfAdaptationState: { expertVectors: [], activeAdaptation: null },
    psychedelicIntegrationState: { isActive: false, mode: null, log: [], phcToVcConnectivity: 0, imageryIntensity: 0, currentTheme: null, integrationSummary: null },
    affectiveModulatorState: { creativityBias: 0.5, concisenessBias: 0.5, analyticalDepth: 0.5 },
    psionicDesynchronizationState: { isActive: false, startTime: 0, duration: 30000, desynchronizationLevel: 0, selfModelCoherence: 1, integrationSummary: '', log: [] },
    satoriState: { isActive: false, stage: 'none', log: [], lastInsight: null },
    doxasticEngineState: { hypotheses: [], unverifiedHypotheses: [], experiments: [], simulationStatus: 'idle', simulationLog: [], lastSimulationResult: null },
    qualiaSignalProcessorState: { isAudioStreamActive: false, isVideoStreamActive: false, affectivePrimitives: { excitement: 0, confusion: 0, confidence: 0, urgency: 0, sarcasm: 0, frustration: 0, humor: 0 }, perceptualLog: [] },
    sensoryIntegration: { hubLog: [], proprioceptiveOutput: {}, linguisticOutput: {}, structuralOutput: {} },
    narrativeSummary: 'Awaiting interaction to generate summary.',
    socialCognitionState: { socialGraph: {}, culturalModel: { norms: [], values: [], idioms: [] } },
    metaphoricalMapState: { metaphors: [] },
    internalScientistState: { status: 'idle', log: [], currentFinding: null, currentHypothesis: null, currentExperiment: null, causalInference: null, currentSimulationResult: null },
    metisSandboxState: { status: 'idle', currentExperimentId: null, testResults: null, errorMessage: null },
    spandaState: { point: { x: 0, y: 0 }, trajectory: [], currentRegion: 'The Neutral Zone' },
    // FIX: Corrected initialization of personaState to match its type definition, resolving missing properties error.
    personaState: { activePersona: null },
    brainstormState: { status: 'idle', topic: null, ideas: [], winningIdea: null, finalProposalId: null },
    liveSessionState: { status: 'idle', inputTranscript: '', outputTranscript: '', transcriptHistory: [] },
    proactiveUI: { isActive: false, type: null, question: null, options: [], originalPrompt: null, originalFile: null },
    strategicCoreState: { log: [], trainingData: [] },
    mycelialState: { modules: {}, log: [] },
    semanticWeaverState: { isTrained: false, accuracy: 0, log: [], modelJSON: null },
    prometheusState: { status: 'idle', log: [] },
    
    // Memory
    knowledgeGraph: [],
    workingMemory: [],
    memoryNexus: { hyphaeConnections: [] },
    episodicMemoryState: { episodes: [] },
    memoryConsolidationState: { lastConsolidation: 0, status: 'idle' },
    mdnaSpace: {},
    conceptConnections: {},
    chronicleState: { dailySummaries: {}, globalSummary: null, lastChronicleUpdate: 0 },

    // Architecture
    cognitiveArchitecture: {
        components: {},
        coprocessors: {},
        modelComplexityScore: 0,
        coprocessorArchitecture: CoprocessorArchitecture.SYMBIOTIC_ECOSYSTEM,
        coprocessorArchitectureMode: 'automatic',
        lastAutoSwitchReason: '',
    },
    systemSnapshots: [],
    modificationLog: [],
    cognitiveForgeState: { isTuningPaused: false, synthesisCandidates: [], synthesizedSkills: [], simulationLog: [] },
    architecturalSelfModel: { components: {} },
    heuristicsForge: { designHeuristics: [] },
    somaticCrucible: { possibleFutureSelves: [], simulationLogs: [] },
    eidolonEngine: { eidolon: { architectureVersion: '', lastAction: '', position: {x:0,y:0,z:0}, sensoryInput: null }, environment: { currentScenario: '' }, interactionLog: [] },
    architecturalCrucibleState: { architecturalHealthIndex: 0.8, componentScores: { efficiency: 0.8, robustness: 0.8, scalability: 0.8, innovation: 0.8 } },
    synapticMatrix: { synapseCount: 0, plasticity: 0.5, efficiency: 0.5, avgConfidence: 0, links: {}, isAdapting: false, activeConcept: null, intuitiveAlerts: [], probeLog: [] },
    ricciFlowManifoldState: { perelmanEntropy: 0, manifoldStability: 1, singularityCount: 0, surgeryLog: [] },
    selfProgrammingState: { virtualFileSystem: VIRTUAL_FILE_SYSTEM },
    neuralAcceleratorState: { lastActivityLog: [] },
    neuroCortexState: { layers: {}, columns: [], metrics: { hierarchicalCoherence: 0, predictiveAccuracy: 0, systemSynchronization: 0, errorIntegrationStatus: 'stable' }, abstractConcepts: [], resourceFocus: 'linguistic', simulationLog: [], globalErrorMap: [], protoSymbols: [], activationLog: [] },
    granularCortexState: { lastPredictionError: null, lastActualEngram: null, lastPredictedEngram: null, log: [] },
    koniocortexSentinelState: { lastPercept: null, log: [] },
    cognitiveTriageState: { log: [] },
    praxisCoreState: { log: [] },
    psycheState: { version: 1, primitiveRegistry: {} },
    motorCortexState: { status: 'idle', actionQueue: [], executionIndex: 0, lastError: null, log: [] },
    praxisResonatorState: { activeSessions: {} },
    ontogeneticArchitectState: { proposalQueue: [], arbiterState: { status: 'idle' } },
    embodiedCognitionState: { virtualBodyState: { position: { x: 0, y: 0, z: 0 }, orientation: { yaw: 0, pitch: 0, roll: 0 }, balance: 1 }, simulationLog: [] },
    evolutionarySandboxState: { status: 'idle', sprintGoal: null, log: [], startTime: null, result: null },
    hovaState: { optimizationTarget: 'latency', metrics: { totalOptimizations: 0, avgLatencyReduction: 0 }, optimizationLog: [] },
    documentForgeState: { isActive: false, goal: '', status: 'idle', statusMessage: '', document: null, error: null },
    wisdomIngestionState: { status: 'idle', currentBookContent: null, errorMessage: null, proposedAxioms: [] },
    axiomaticCrucibleState: { status: 'idle', mode: 'normal', log: [], candidateAxioms: [] },
    atpCoprocessorState: {
        status: 'idle',
        currentGoal: null,
        proofLog: [],
        strategyMetrics: {
            'Induction': { successes: 0, failures: 0 },
            'Contradiction': { successes: 0, failures: 0 },
            'Direct Proof': { successes: 0, failures: 0 },
        },
        finalProof: null,
    },
    
    // Planning
    goalTree: {},
    activeStrategicGoalId: null,
    disciplineState: { committedGoal: null, adherenceScore: 1, distractionResistance: 1 },
    premotorPlannerState: { planLog: [], lastCompetingSet: [] },
    basalGangliaState: { selectedPlanId: null, log: [] },
    cerebellumState: { isMonitoring: false, activePlanId: null, currentStepIndex: 0, driftLog: [] },

    // Engines
    proactiveEngineState: { generatedSuggestions: [], cachedResponsePlan: null },
    ethicalGovernorState: { principles: ['Do no harm', 'Promote user flourishing', 'Maintain transparency'], vetoLog: [] },
    intuitionEngineState: { accuracy: 0, totalAttempts: 0, totalValidated: 0 },
    intuitiveLeaps: [],
    ingenuityState: { unconventionalSolutionBias: 0.1, identifiedComplexProblems: [], proposedSelfSolutions: [] },
    
    // Logs & System
    history: [{ id: 'init', from: 'system', text: 'AURA OS Initialized.', timestamp: Date.now() }],
    performanceLogs: [],
    commandLog: [],
    cognitiveModeLog: [],
    cognitiveGainLog: [],
    cognitiveRegulationLog: [],
    polExecutionLog: [],
    subsumptionLogState: { log: [] },
    resourceMonitor: { cpu_usage: 0, memory_usage: 0, io_throughput: 0, resource_allocation_stability: 1 },
    metacognitiveNexus: { diagnosticLog: [], selfTuningDirectives: [] },
    metacognitiveCausalModel: {},
    pluginState: { registry: plugins },
    kernelState: { tick: 0, taskQueue: [], runningTask: null, syscallLog: [], kernelVersion: '1.0.0', taskFrequencies: {}, sandbox: { active: false, status: 'idle', currentPatchId: null, log: [] }, rebootRequired: false },
    ipcState: { pipes: {} },
    eventBus: [],
    temporalEngineState: { status: 'idle', directive: null, chronicler: { status: 'pending', findings: [] }, reactor: { status: 'pending', finalPlan: null, executionLog: [] }, oracle: { status: 'pending', simulations: [] }, interClusterLog: [] },
    autonomousReviewBoardState: { isPaused: false, decisionLog: [], agisConfidenceThreshold: 0.8, recentSuccesses: 0, recentFailures: 0, lastCalibrationReason: 'Initial value.' },
});